/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feec.cz.brno.speechproc.gui.formants;

import au.com.bytecode.opencsv.CSVReader;
import com.google.common.primitives.Doubles;
import feec.cz.brno.speechproc.calc.api.formants.IFormants;
import feec.cz.brno.speechproc.calc.utility.CalcUtilities;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.results.GraphWindow;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.math3.stat.descriptive.rank.Percentile;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author hynstm
 */
public class FormantsResultPanel extends javax.swing.JPanel {
    
    private final static Logger logger = LogManager.getLogger(FormantsResultPanel.class);

    private File csvResultFile;
    private DefaultTableModel formantTableModel;
    
    private final File sourceSoundFile;
    private GraphWindow formantsGraph;
    
    /**
     * Creates new form FormantsResultPanel
     * @param sourceSoundFile
     * @param csvResultFile
     */
    public FormantsResultPanel(File sourceSoundFile, File csvResultFile) {
        this.sourceSoundFile = sourceSoundFile;
        this.csvResultFile = csvResultFile;
        initComponents();
        loadFormantsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        formantTableModel = new DefaultTableModel();
        formantsTable = new javax.swing.JTable(formantTableModel);
        infoPanel = new javax.swing.JPanel();
        formant2Panel = new javax.swing.JPanel();
        meanDescriptionF2Label = new javax.swing.JLabel();
        meanF2Label = new javax.swing.JLabel();
        medianDescriptionF2Label = new javax.swing.JLabel();
        medianF2Label = new javax.swing.JLabel();
        stedvF2DescriptionLabel = new javax.swing.JLabel();
        stdevF2ValueLabel = new javax.swing.JLabel();
        minF2DescriptionLabel = new javax.swing.JLabel();
        minF2ValueLabel = new javax.swing.JLabel();
        maxF2DescriptionLabel = new javax.swing.JLabel();
        maxF2ValueLabel = new javax.swing.JLabel();
        varianceF2DescriptionLabel = new javax.swing.JLabel();
        varianceF2ValueLabel = new javax.swing.JLabel();
        firstPerF2DescriptionLabel = new javax.swing.JLabel();
        firstPerF2ValueLabel = new javax.swing.JLabel();
        ninePerF2DescriptionLabel = new javax.swing.JLabel();
        ninePerF2ValueLabel = new javax.swing.JLabel();
        irF2DescriptionLabel = new javax.swing.JLabel();
        irF2ValueLabel = new javax.swing.JLabel();
        formant3Panel = new javax.swing.JPanel();
        meanDescriptionF3Label = new javax.swing.JLabel();
        meanF3Label = new javax.swing.JLabel();
        medianDescriptionF3Label = new javax.swing.JLabel();
        medianF3Label = new javax.swing.JLabel();
        stdevF3DescriptionLabel = new javax.swing.JLabel();
        stdevF3ValueLabel = new javax.swing.JLabel();
        minF3DescriptionLabel = new javax.swing.JLabel();
        minF3ValueLabel = new javax.swing.JLabel();
        maxF3DescriptionLabel = new javax.swing.JLabel();
        maxF3ValueLabel = new javax.swing.JLabel();
        varianceF3DescriptionLabel = new javax.swing.JLabel();
        varianceF3ValueLabel = new javax.swing.JLabel();
        firstPerF3DescriptionLabel = new javax.swing.JLabel();
        firstPerF3ValueLabel = new javax.swing.JLabel();
        ninePerF3DescriptionLabel = new javax.swing.JLabel();
        ninePerF3ValueLabel = new javax.swing.JLabel();
        irF3DescriptionLabel = new javax.swing.JLabel();
        irF3ValueLabel = new javax.swing.JLabel();
        showGraphButton = new javax.swing.JButton(Icons.GRAPH_ICON);
        formant1Panel = new javax.swing.JPanel();
        meanDescriptionF1Label = new javax.swing.JLabel();
        meanF1Label = new javax.swing.JLabel();
        medianDescriptionF1Label = new javax.swing.JLabel();
        medianF1Label = new javax.swing.JLabel();
        stdevF1DescriptionLabel = new javax.swing.JLabel();
        stdevF1ValueLabel = new javax.swing.JLabel();
        minF1DescriptionLabel = new javax.swing.JLabel();
        minF1ValueLabel = new javax.swing.JLabel();
        maxF1DescriptionLabel = new javax.swing.JLabel();
        maxF1ValueLabel = new javax.swing.JLabel();
        varianceF1DescriptionLabel = new javax.swing.JLabel();
        varianceF1ValueLabel = new javax.swing.JLabel();
        firstPerF1DescriptionLabel = new javax.swing.JLabel();
        firstPerF1ValueLabel = new javax.swing.JLabel();
        ninePerF1DescriptionLabel = new javax.swing.JLabel();
        ninePerF1ValueLabel = new javax.swing.JLabel();
        irF1DescriptionLabel = new javax.swing.JLabel();
        irF1ValueLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        formantsTable.setModel(formantTableModel);
        tableScrollPane.setViewportView(formantsTable);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);

        formant2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 2"));

        meanDescriptionF2Label.setText("Mean:");

        meanF2Label.setText("jLabel7");

        medianDescriptionF2Label.setText("Median:");

        medianF2Label.setText("jLabel7");

        stedvF2DescriptionLabel.setText("Stdev");

        stdevF2ValueLabel.setText("jLabel1");

        minF2DescriptionLabel.setText("Min:");

        minF2ValueLabel.setText("jLabel1");

        maxF2DescriptionLabel.setText("Max:");

        maxF2ValueLabel.setText("jLabel2");

        varianceF2DescriptionLabel.setText("Variance:");

        varianceF2ValueLabel.setText("jLabel2");

        firstPerF2DescriptionLabel.setText("1.p:");

        firstPerF2ValueLabel.setText("jLabel2");

        ninePerF2DescriptionLabel.setText("99.p:");

        ninePerF2ValueLabel.setText("jLabel4");

        irF2DescriptionLabel.setText("IR:");

        irF2ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant2PanelLayout = new javax.swing.GroupLayout(formant2Panel);
        formant2Panel.setLayout(formant2PanelLayout);
        formant2PanelLayout.setHorizontalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianDescriptionF2Label)
                    .addComponent(meanDescriptionF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stedvF2DescriptionLabel)
                    .addComponent(minF2DescriptionLabel)
                    .addComponent(maxF2DescriptionLabel)
                    .addComponent(varianceF2DescriptionLabel)
                    .addComponent(firstPerF2DescriptionLabel)
                    .addComponent(ninePerF2DescriptionLabel)
                    .addComponent(irF2DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(medianF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdevF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formant2PanelLayout.createSequentialGroup()
                        .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstPerF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(ninePerF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(irF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant2PanelLayout.setVerticalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanDescriptionF2Label)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianF2Label)
                    .addComponent(medianDescriptionF2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stedvF2DescriptionLabel)
                    .addComponent(stdevF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceF2DescriptionLabel)
                    .addComponent(varianceF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF2DescriptionLabel)
                    .addComponent(minF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxF2DescriptionLabel)
                    .addComponent(maxF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF2DescriptionLabel)
                    .addComponent(firstPerF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF2DescriptionLabel)
                    .addComponent(ninePerF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(irF2DescriptionLabel)
                    .addComponent(irF2ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        formant3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 3"));

        meanDescriptionF3Label.setText("Mean:");

        meanF3Label.setText("jLabel8");

        medianDescriptionF3Label.setText("Median:");

        medianF3Label.setText("jLabel9");

        stdevF3DescriptionLabel.setText("Stdev:");

        stdevF3ValueLabel.setText("jLabel2");

        minF3DescriptionLabel.setText("Min:");

        minF3ValueLabel.setText("jLabel2");

        maxF3DescriptionLabel.setText("Max:");

        maxF3ValueLabel.setText("jLabel2");

        varianceF3DescriptionLabel.setText("Variance:");

        varianceF3ValueLabel.setText("jLabel2");

        firstPerF3DescriptionLabel.setText("1.p:");

        firstPerF3ValueLabel.setText("jLabel2");

        ninePerF3DescriptionLabel.setText("99.p:");

        ninePerF3ValueLabel.setText("jLabel4");

        irF3DescriptionLabel.setText("IR:");

        irF3ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant3PanelLayout = new javax.swing.GroupLayout(formant3Panel);
        formant3Panel.setLayout(formant3PanelLayout);
        formant3PanelLayout.setHorizontalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionF3Label)
                    .addComponent(stdevF3DescriptionLabel)
                    .addComponent(minF3DescriptionLabel)
                    .addComponent(maxF3DescriptionLabel)
                    .addComponent(varianceF3DescriptionLabel)
                    .addComponent(firstPerF3DescriptionLabel)
                    .addComponent(ninePerF3DescriptionLabel)
                    .addComponent(irF3DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdevF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant3PanelLayout.setVerticalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionF3Label)
                    .addComponent(medianF3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevF3DescriptionLabel)
                    .addComponent(stdevF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceF3DescriptionLabel)
                    .addComponent(varianceF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF3DescriptionLabel)
                    .addComponent(minF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxF3DescriptionLabel)
                    .addComponent(maxF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF3DescriptionLabel)
                    .addComponent(firstPerF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF3DescriptionLabel)
                    .addComponent(ninePerF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irF3DescriptionLabel)
                    .addComponent(irF3ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showGraphButton.setText("Show graph");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        formant1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 1"));

        meanDescriptionF1Label.setText("Mean: ");

        meanF1Label.setText("jLabel2");

        medianDescriptionF1Label.setText("Median:");

        medianF1Label.setText("jLabel3");

        stdevF1DescriptionLabel.setText("Stdev:");

        stdevF1ValueLabel.setText("jLabel2");

        minF1DescriptionLabel.setText("Min:");

        minF1ValueLabel.setText("jLabel1");

        maxF1DescriptionLabel.setText("Max:");

        maxF1ValueLabel.setText("jLabel1");

        varianceF1DescriptionLabel.setText("Variance:");

        varianceF1ValueLabel.setText("jLabel1");

        firstPerF1DescriptionLabel.setText("1.p:");

        firstPerF1ValueLabel.setText("jLabel2");

        ninePerF1DescriptionLabel.setText("99.p:");

        ninePerF1ValueLabel.setText("jLabel2");

        irF1DescriptionLabel.setText("IR:");

        irF1ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant1PanelLayout = new javax.swing.GroupLayout(formant1Panel);
        formant1Panel.setLayout(formant1PanelLayout);
        formant1PanelLayout.setHorizontalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdevF1DescriptionLabel)
                    .addComponent(meanDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varianceF1DescriptionLabel)
                    .addComponent(minF1DescriptionLabel)
                    .addComponent(maxF1DescriptionLabel)
                    .addComponent(firstPerF1DescriptionLabel)
                    .addComponent(ninePerF1DescriptionLabel)
                    .addComponent(irF1DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanF1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdevF1ValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF1ValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant1PanelLayout.setVerticalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meanF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanDescriptionF1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stdevF1DescriptionLabel)
                    .addComponent(stdevF1ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(varianceF1DescriptionLabel)
                    .addComponent(varianceF1ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF1DescriptionLabel)
                    .addComponent(minF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formant1PanelLayout.createSequentialGroup()
                        .addComponent(maxF1DescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(maxF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF1DescriptionLabel)
                    .addComponent(firstPerF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF1DescriptionLabel)
                    .addComponent(ninePerF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irF1DescriptionLabel)
                    .addComponent(irF1ValueLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formant1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showGraphButton)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showGraphButton)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formant3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formant2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formant1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(infoPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        logger.debug("Showing formants chart from " + csvResultFile.getName());
        if (formantsGraph == null) {
            FormantCharts graph = new FormantCharts();
            formantsGraph = new GraphWindow(csvResultFile.getAbsolutePath(), graph.createChart(csvResultFile));
            formantsGraph.setVisible(true);
        } else {
            formantsGraph.setVisible(true);
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void loadFormantsTable() {
        String[] csvLine;
        List<Double> formant1 = new ArrayList<>();
        List<Double> formant2 = new ArrayList<>();
        List<Double> formant3 = new ArrayList<>();
        CSVReader reader = null;
        try {
            reader = new CSVReader(new FileReader(csvResultFile));
            String[] header = reader.readNext();
            formantTableModel.setColumnIdentifiers(header);
            while ((csvLine = reader.readNext()) != null) {
                formantTableModel.addRow(csvLine);
                try { formant1.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_1])); } catch (NumberFormatException e) {}
                try { formant2.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_2])); } catch (NumberFormatException e) {}
                try { formant3.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_3])); } catch (NumberFormatException e) {}
            }
            reader.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load formants table from CSV file!", "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load formants table from CSV file!", ex);
        }
        formantsTable.setModel(formantTableModel);
        formantTableModel.fireTableDataChanged();
   
        meanF1Label.setText(CalcUtilities.mean(formant1) + " Hz");
        meanF2Label.setText(CalcUtilities.mean(formant2) + " Hz");
        meanF3Label.setText(CalcUtilities.mean(formant3) + " Hz");

        medianF1Label.setText(CalcUtilities.median(formant1) + " Hz");
        medianF2Label.setText(CalcUtilities.median(formant2) + " Hz");
        medianF3Label.setText(CalcUtilities.median(formant3) + " Hz");
        
        stdevF1ValueLabel.setText(CalcUtilities.stdev(formant1) + " Hz");
        stdevF2ValueLabel.setText(CalcUtilities.stdev(formant2) + " Hz");
        stdevF3ValueLabel.setText(CalcUtilities.stdev(formant3) + " Hz");
        
        varianceF1ValueLabel.setText(CalcUtilities.variance(formant1) + " Hz");
        varianceF2ValueLabel.setText(CalcUtilities.variance(formant2) + " Hz");
        varianceF3ValueLabel.setText(CalcUtilities.variance(formant3) + " Hz");
        
        minF1ValueLabel.setText(Collections.min(formant1) + " Hz");
        minF2ValueLabel.setText(Collections.min(formant2) + " Hz");
        minF3ValueLabel.setText(Collections.min(formant3) + " Hz");
        
        maxF1ValueLabel.setText(Collections.max(formant1) + " Hz");
        maxF2ValueLabel.setText(Collections.max(formant2) + " Hz");
        maxF3ValueLabel.setText(Collections.max(formant3) + " Hz");
        
        Percentile percentile = new Percentile(0.1);
        double firstPerF1 = percentile.evaluate(Doubles.toArray(formant1));
        double firstPerF2 = percentile.evaluate(Doubles.toArray(formant2));
        double firstPerF3 = percentile.evaluate(Doubles.toArray(formant3));
        firstPerF1ValueLabel.setText(firstPerF1 + " Hz");
        firstPerF2ValueLabel.setText(firstPerF2 + " Hz");
        firstPerF3ValueLabel.setText(firstPerF3 + " Hz");
        
        percentile = new Percentile(0.99);
        double ninePerF1 = percentile.evaluate(Doubles.toArray(formant1));
        double ninePerF2 = percentile.evaluate(Doubles.toArray(formant2));
        double ninePerF3 = percentile.evaluate(Doubles.toArray(formant3));
        ninePerF1ValueLabel.setText(ninePerF1 + " Hz");
        ninePerF2ValueLabel.setText(ninePerF2 + " Hz");
        ninePerF3ValueLabel.setText(ninePerF3 + " Hz");
        
//        irF1ValueLabel.setText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstPerF1DescriptionLabel;
    private javax.swing.JLabel firstPerF1ValueLabel;
    private javax.swing.JLabel firstPerF2DescriptionLabel;
    private javax.swing.JLabel firstPerF2ValueLabel;
    private javax.swing.JLabel firstPerF3DescriptionLabel;
    private javax.swing.JLabel firstPerF3ValueLabel;
    private javax.swing.JPanel formant1Panel;
    private javax.swing.JPanel formant2Panel;
    private javax.swing.JPanel formant3Panel;
    private javax.swing.JTable formantsTable;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel irF1DescriptionLabel;
    private javax.swing.JLabel irF1ValueLabel;
    private javax.swing.JLabel irF2DescriptionLabel;
    private javax.swing.JLabel irF2ValueLabel;
    private javax.swing.JLabel irF3DescriptionLabel;
    private javax.swing.JLabel irF3ValueLabel;
    private javax.swing.JLabel maxF1DescriptionLabel;
    private javax.swing.JLabel maxF1ValueLabel;
    private javax.swing.JLabel maxF2DescriptionLabel;
    private javax.swing.JLabel maxF2ValueLabel;
    private javax.swing.JLabel maxF3DescriptionLabel;
    private javax.swing.JLabel maxF3ValueLabel;
    private javax.swing.JLabel meanDescriptionF1Label;
    private javax.swing.JLabel meanDescriptionF2Label;
    private javax.swing.JLabel meanDescriptionF3Label;
    private javax.swing.JLabel meanF1Label;
    private javax.swing.JLabel meanF2Label;
    private javax.swing.JLabel meanF3Label;
    private javax.swing.JLabel medianDescriptionF1Label;
    private javax.swing.JLabel medianDescriptionF2Label;
    private javax.swing.JLabel medianDescriptionF3Label;
    private javax.swing.JLabel medianF1Label;
    private javax.swing.JLabel medianF2Label;
    private javax.swing.JLabel medianF3Label;
    private javax.swing.JLabel minF1DescriptionLabel;
    private javax.swing.JLabel minF1ValueLabel;
    private javax.swing.JLabel minF2DescriptionLabel;
    private javax.swing.JLabel minF2ValueLabel;
    private javax.swing.JLabel minF3DescriptionLabel;
    private javax.swing.JLabel minF3ValueLabel;
    private javax.swing.JLabel ninePerF1DescriptionLabel;
    private javax.swing.JLabel ninePerF1ValueLabel;
    private javax.swing.JLabel ninePerF2DescriptionLabel;
    private javax.swing.JLabel ninePerF2ValueLabel;
    private javax.swing.JLabel ninePerF3DescriptionLabel;
    private javax.swing.JLabel ninePerF3ValueLabel;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JLabel stdevF1DescriptionLabel;
    private javax.swing.JLabel stdevF1ValueLabel;
    private javax.swing.JLabel stdevF2ValueLabel;
    private javax.swing.JLabel stdevF3DescriptionLabel;
    private javax.swing.JLabel stdevF3ValueLabel;
    private javax.swing.JLabel stedvF2DescriptionLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel varianceF1DescriptionLabel;
    private javax.swing.JLabel varianceF1ValueLabel;
    private javax.swing.JLabel varianceF2DescriptionLabel;
    private javax.swing.JLabel varianceF2ValueLabel;
    private javax.swing.JLabel varianceF3DescriptionLabel;
    private javax.swing.JLabel varianceF3ValueLabel;
    // End of variables declaration//GEN-END:variables
}
