/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feec.cz.brno.speechproc.gui.formants;

import au.com.bytecode.opencsv.CSVReader;
import feec.cz.brno.speechproc.calc.api.formants.IFormants;
import feec.cz.brno.speechproc.calc.utility.CalcUtilities;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.results.GraphWindow;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author hynstm
 */
public class FormantsResultPanel extends javax.swing.JPanel {
    
    private final static Logger logger = LogManager.getLogger(FormantsResultPanel.class);

    private File csvResultFile;
    private DefaultTableModel formantTableModel;
    
    private final File sourceSoundFile;
    private GraphWindow formantsGraph;
    
    /**
     * Creates new form FormantsResultPanel
     * @param sourceSoundFile
     * @param csvResultFile
     * @param mean
     * @param median
     */
    public FormantsResultPanel(File sourceSoundFile, File csvResultFile) {
        this.sourceSoundFile = sourceSoundFile;
        this.csvResultFile = csvResultFile;
        initComponents();
        loadFormantsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        formantTableModel = new DefaultTableModel();
        formantsTable = new javax.swing.JTable(formantTableModel);
        infoPanel = new javax.swing.JPanel();
        formant2Panel = new javax.swing.JPanel();
        meanDescriptionF2Label = new javax.swing.JLabel();
        meanF2Label = new javax.swing.JLabel();
        medianDescriptionF2Label = new javax.swing.JLabel();
        medianF2Label = new javax.swing.JLabel();
        formant3Panel = new javax.swing.JPanel();
        meanDescriptionF3Label = new javax.swing.JLabel();
        meanF3Label = new javax.swing.JLabel();
        medianDescriptionF3Label = new javax.swing.JLabel();
        medianF3Label = new javax.swing.JLabel();
        showGraphButton = new javax.swing.JButton(Icons.GRAPH_ICON);
        formant1Panel = new javax.swing.JPanel();
        meanDescriptionF1Label = new javax.swing.JLabel();
        meanF1Label = new javax.swing.JLabel();
        medianDescriptionF1Label = new javax.swing.JLabel();
        medianF1Label = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        formantsTable.setModel(formantTableModel);
        tableScrollPane.setViewportView(formantsTable);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);

        formant2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 2"));

        meanDescriptionF2Label.setText("Mean:");

        meanF2Label.setText("jLabel7");

        medianDescriptionF2Label.setText("Median:");

        medianF2Label.setText("jLabel7");

        javax.swing.GroupLayout formant2PanelLayout = new javax.swing.GroupLayout(formant2Panel);
        formant2Panel.setLayout(formant2PanelLayout);
        formant2PanelLayout.setHorizontalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianDescriptionF2Label)
                    .addComponent(meanDescriptionF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(medianF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant2PanelLayout.setVerticalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanDescriptionF2Label)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianF2Label)
                    .addComponent(medianDescriptionF2Label))
                .addContainerGap())
        );

        formant3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 3"));

        meanDescriptionF3Label.setText("Mean:");

        meanF3Label.setText("jLabel8");

        medianDescriptionF3Label.setText("Median:");

        medianF3Label.setText("jLabel9");

        javax.swing.GroupLayout formant3PanelLayout = new javax.swing.GroupLayout(formant3Panel);
        formant3Panel.setLayout(formant3PanelLayout);
        formant3PanelLayout.setHorizontalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionF3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant3PanelLayout.setVerticalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionF3Label)
                    .addComponent(medianF3Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showGraphButton.setText("Show graph");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        formant1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 1"));

        meanDescriptionF1Label.setText("Mean: ");

        meanF1Label.setText("jLabel2");

        medianDescriptionF1Label.setText("Median:");

        medianF1Label.setText("jLabel3");

        javax.swing.GroupLayout formant1PanelLayout = new javax.swing.GroupLayout(formant1Panel);
        formant1Panel.setLayout(formant1PanelLayout);
        formant1PanelLayout.setHorizontalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formant1PanelLayout.createSequentialGroup()
                        .addComponent(meanDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(meanF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formant1PanelLayout.createSequentialGroup()
                        .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(medianF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formant1PanelLayout.setVerticalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meanF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanDescriptionF1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF1Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formant1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(showGraphButton)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showGraphButton)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formant3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formant2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formant1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(infoPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        if (formantsGraph == null) {
            FormantCharts graph = new FormantCharts();
            formantsGraph = new GraphWindow(csvResultFile.getAbsolutePath(), graph.createFormantChart(csvResultFile));
            formantsGraph.setVisible(true);
            logger.debug("Showing formant chart from " + csvResultFile.getName());
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void loadFormantsTable() {
        String[] csvLine;
        List<Double> formant1 = new ArrayList<>();
        List<Double> formant2 = new ArrayList<>();
        List<Double> formant3 = new ArrayList<>();
        CSVReader reader = null;
        try {
            reader = new CSVReader(new FileReader(csvResultFile));
            String[] header = reader.readNext();
            formantTableModel.setColumnIdentifiers(header);
            while ((csvLine = reader.readNext()) != null) {
                formantTableModel.addRow(csvLine);
                try { formant1.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_1])); } catch (NumberFormatException e) {}
                try { formant2.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_2])); } catch (NumberFormatException e) {}
                try { formant3.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_3])); } catch (NumberFormatException e) {}
            }
            reader.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load formants table from CSV file!", "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load formants table from CSV file!", ex);
        }
        formantsTable.setModel(formantTableModel);
        formantTableModel.fireTableDataChanged();
        
            meanF1Label.setText(CalcUtilities.mean(formant1) + " Hz");
            meanF2Label.setText(CalcUtilities.mean(formant2) + " Hz");
            meanF3Label.setText(CalcUtilities.mean(formant3) + " Hz");
        
            medianF1Label.setText(CalcUtilities.median(formant1) + " Hz");
            medianF2Label.setText(CalcUtilities.median(formant2) + " Hz");
            medianF3Label.setText(CalcUtilities.median(formant3) + " Hz");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formant1Panel;
    private javax.swing.JPanel formant2Panel;
    private javax.swing.JPanel formant3Panel;
    private javax.swing.JTable formantsTable;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel meanDescriptionF1Label;
    private javax.swing.JLabel meanDescriptionF2Label;
    private javax.swing.JLabel meanDescriptionF3Label;
    private javax.swing.JLabel meanF1Label;
    private javax.swing.JLabel meanF2Label;
    private javax.swing.JLabel meanF3Label;
    private javax.swing.JLabel medianDescriptionF1Label;
    private javax.swing.JLabel medianDescriptionF2Label;
    private javax.swing.JLabel medianDescriptionF3Label;
    private javax.swing.JLabel medianF1Label;
    private javax.swing.JLabel medianF2Label;
    private javax.swing.JLabel medianF3Label;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
