/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feec.cz.brno.speechproc.gui.f0;

import au.com.bytecode.opencsv.CSVReader;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.results.GraphWindow;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author mira
 */
public class F0ResultPanel extends javax.swing.JPanel {
    
    private final static Logger logger = LogManager.getLogger(F0ResultPanel.class);
    
    private final DefaultTableModel f0TableModel = new DefaultTableModel();
    
    private final File csvResultFile;
    private final File csvStatsFile;
    private final File sourceSoundFile;
    
    private GraphWindow formantsGraph;

    /**
     * Creates new form F0ResultPanel
     * @param sourceSoundFile
     * @param csvResultFile
     * @param csvStatsFile
     */
    public F0ResultPanel(File sourceSoundFile, File csvResultFile, File csvStatsFile) {
        this.csvResultFile = csvResultFile;
        this.csvStatsFile = csvStatsFile;
        this.sourceSoundFile = sourceSoundFile;
        initComponents();
        loadF0Table();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        showGraphButton = new javax.swing.JButton(Icons.GRAPH_ICON);
        jPanel2 = new javax.swing.JPanel();
        meanDescriptionLabel = new javax.swing.JLabel();
        medianDescriptionLabel = new javax.swing.JLabel();
        medianValuleLabel = new javax.swing.JLabel();
        meanValueLabel = new javax.swing.JLabel();
        stdevDescriptionLabel = new javax.swing.JLabel();
        stdevValueLabel = new javax.swing.JLabel();
        minDescriptionLabel = new javax.swing.JLabel();
        minValueLabel = new javax.swing.JLabel();
        maxDescriptionLabel = new javax.swing.JLabel();
        maxValueLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jitterLocDescriptionLabel = new javax.swing.JLabel();
        jitterLocValueLabel = new javax.swing.JLabel();
        jitterLocAbsDescriptionLabel = new javax.swing.JLabel();
        jitterLocAbsValueLabel = new javax.swing.JLabel();
        jitterRapDescriptionLabel = new javax.swing.JLabel();
        jitterRapValueLabel = new javax.swing.JLabel();
        jitterPpq5DescriptionLabel = new javax.swing.JLabel();
        jitterDdpDescriptionLabel = new javax.swing.JLabel();
        jitterPpq5ValueLabel = new javax.swing.JLabel();
        jitterDdpValueLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        shimmerLocDescriptionLabel = new javax.swing.JLabel();
        shimmerLocValueLabel = new javax.swing.JLabel();
        shimmerLocDbDescriptionLabel = new javax.swing.JLabel();
        shimmerLocDbValueLabel = new javax.swing.JLabel();
        shimmerApq3DescriptionLabel = new javax.swing.JLabel();
        shimmerApq3ValueLabel = new javax.swing.JLabel();
        shimmerApq5DescriptionLabel = new javax.swing.JLabel();
        shimmerApq5ValueLabel = new javax.swing.JLabel();
        shimmerApq11DescriptionLabel = new javax.swing.JLabel();
        shimmerApq11ValueLabel = new javax.swing.JLabel();
        shimmerDdaDescriptionLabel = new javax.swing.JLabel();
        shimmerDdaValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        f0Table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        showGraphButton.setText("Show graph");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("F0 info"));

        meanDescriptionLabel.setText("F0 mean:");

        medianDescriptionLabel.setText("F0 median:");

        medianValuleLabel.setText("jLabel1");

        meanValueLabel.setText("jLabel1");

        stdevDescriptionLabel.setText("F0 stdev:");

        stdevValueLabel.setText("jLabel1");

        minDescriptionLabel.setText("F0 min:");

        minValueLabel.setText("jLabel1");

        maxDescriptionLabel.setText("F0 max:");

        maxValueLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianDescriptionLabel)
                            .addComponent(meanDescriptionLabel))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianValuleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meanValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdevDescriptionLabel)
                            .addComponent(minDescriptionLabel)
                            .addComponent(maxDescriptionLabel))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stdevValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meanDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionLabel)
                    .addComponent(medianValuleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevDescriptionLabel)
                    .addComponent(stdevValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minDescriptionLabel)
                    .addComponent(minValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDescriptionLabel)
                    .addComponent(maxValueLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jitter"));

        jitterLocDescriptionLabel.setText("Jitter (local):");

        jitterLocValueLabel.setText("jLabel1");

        jitterLocAbsDescriptionLabel.setText("Jitter (local, absolute):");

        jitterLocAbsValueLabel.setText("jLabel1");

        jitterRapDescriptionLabel.setText("Jitter (rap): ");

        jitterRapValueLabel.setText("jLabel1");

        jitterPpq5DescriptionLabel.setText("Jitter (ppq5):");

        jitterDdpDescriptionLabel.setText("Jitter (ddp):");

        jitterPpq5ValueLabel.setText("jLabel1");

        jitterDdpValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jitterLocAbsDescriptionLabel)
                    .addComponent(jitterRapDescriptionLabel)
                    .addComponent(jitterPpq5DescriptionLabel)
                    .addComponent(jitterDdpDescriptionLabel)
                    .addComponent(jitterLocDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jitterLocAbsValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jitterRapValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterLocValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterPpq5ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterDdpValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterLocDescriptionLabel)
                    .addComponent(jitterLocValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterLocAbsDescriptionLabel)
                    .addComponent(jitterLocAbsValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterRapDescriptionLabel)
                    .addComponent(jitterRapValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterPpq5DescriptionLabel)
                    .addComponent(jitterPpq5ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterDdpDescriptionLabel)
                    .addComponent(jitterDdpValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Shimmer"));

        shimmerLocDescriptionLabel.setText("Shimmer (local):");

        shimmerLocValueLabel.setText("jLabel1");

        shimmerLocDbDescriptionLabel.setText("Shimmer (local, dB):");

        shimmerLocDbValueLabel.setText("jLabel1");

        shimmerApq3DescriptionLabel.setText("Shimmer (apq3):");

        shimmerApq3ValueLabel.setText("jLabel1");

        shimmerApq5DescriptionLabel.setText("Shimmer (apq5):");

        shimmerApq5ValueLabel.setText("jLabel2");

        shimmerApq11DescriptionLabel.setText("Shimmer (apq11):");

        shimmerApq11ValueLabel.setText("jLabel2");

        shimmerDdaDescriptionLabel.setText("Shimmer (dda):");

        shimmerDdaValueLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shimmerLocDbDescriptionLabel)
                    .addComponent(shimmerLocDescriptionLabel)
                    .addComponent(shimmerApq3DescriptionLabel)
                    .addComponent(shimmerApq5DescriptionLabel)
                    .addComponent(shimmerApq11DescriptionLabel)
                    .addComponent(shimmerDdaDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shimmerLocDbValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(shimmerLocValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq5ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq11ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerDdaValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerLocDescriptionLabel)
                    .addComponent(shimmerLocValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerLocDbDescriptionLabel)
                    .addComponent(shimmerLocDbValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq3DescriptionLabel)
                    .addComponent(shimmerApq3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq5DescriptionLabel)
                    .addComponent(shimmerApq5ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq11DescriptionLabel)
                    .addComponent(shimmerApq11ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerDdaDescriptionLabel)
                    .addComponent(shimmerDdaValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(showGraphButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showGraphButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        f0Table.setModel(f0TableModel);
        jScrollPane2.setViewportView(f0Table);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        if (formantsGraph == null) {
            F0PitchCharts charts = new F0PitchCharts();
            formantsGraph = new GraphWindow(csvResultFile.getAbsolutePath(), charts.createF0Chart(csvResultFile));
            formantsGraph.setVisible(true);
            logger.debug("Showing pitch chart from " + csvResultFile.getName());
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void loadF0Table() {
        String[] csvLine = null;
        try {
            CSVReader reader = new CSVReader(new FileReader(csvResultFile), ' ');
            reader.readNext();
            f0TableModel.setColumnIdentifiers(new String[] {"Time min (s)", "Time max (s)", "F0 mean (Hz)", "F0 min (Hz)", "F0 max (Hz)", "F0 stdev (Hz)", "F0 VR (Hz)", "rel F0 stdev (%)", "rel F0 VR (%)"});
            while ((csvLine = reader.readNext()) != null) {
                f0TableModel.addRow(csvLine);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load pitch table from CSV file " + csvResultFile.getName(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load formants table from CSV file!", ex);
        }
        f0Table.setModel(f0TableModel);
        f0TableModel.fireTableDataChanged();
        
        try {
            CSVReader reader = new CSVReader(new FileReader(csvStatsFile), ' ');
            reader.readNext();
            csvLine = reader.readNext();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load pitch table from CSV file " + csvStatsFile.getName(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load pitch table from CSV file!", ex);
        }
        // jitter
        jitterLocValueLabel.setText(csvLine[0]);
        jitterLocAbsValueLabel.setText(csvLine[1]);
        jitterRapValueLabel.setText(csvLine[2]);
        jitterPpq5ValueLabel.setText(csvLine[3]);
        jitterDdpValueLabel.setText(csvLine[4]);
        
        // shimmer
        shimmerLocValueLabel.setText(csvLine[5]);
        shimmerLocDbValueLabel.setText(csvLine[6]);
        shimmerApq3ValueLabel.setText(csvLine[7]);
        shimmerApq5ValueLabel.setText(csvLine[8]);
        shimmerApq11ValueLabel.setText(csvLine[9]);
        shimmerDdaValueLabel.setText(csvLine[10]);

        // other
        meanValueLabel.setText(csvLine[11] + " Hz");
        medianValuleLabel.setText(csvLine[12] + " Hz");
        stdevValueLabel.setText(csvLine[13] + " Hz");
        stdevValueLabel.setVisible(true);
        minValueLabel.setText(csvLine[14] + " Hz");
        maxValueLabel.setText(csvLine[15] + " Hz");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable f0Table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jitterDdpDescriptionLabel;
    private javax.swing.JLabel jitterDdpValueLabel;
    private javax.swing.JLabel jitterLocAbsDescriptionLabel;
    private javax.swing.JLabel jitterLocAbsValueLabel;
    private javax.swing.JLabel jitterLocDescriptionLabel;
    private javax.swing.JLabel jitterLocValueLabel;
    private javax.swing.JLabel jitterPpq5DescriptionLabel;
    private javax.swing.JLabel jitterPpq5ValueLabel;
    private javax.swing.JLabel jitterRapDescriptionLabel;
    private javax.swing.JLabel jitterRapValueLabel;
    private javax.swing.JLabel maxDescriptionLabel;
    private javax.swing.JLabel maxValueLabel;
    private javax.swing.JLabel meanDescriptionLabel;
    private javax.swing.JLabel meanValueLabel;
    private javax.swing.JLabel medianDescriptionLabel;
    private javax.swing.JLabel medianValuleLabel;
    private javax.swing.JLabel minDescriptionLabel;
    private javax.swing.JLabel minValueLabel;
    private javax.swing.JLabel shimmerApq11DescriptionLabel;
    private javax.swing.JLabel shimmerApq11ValueLabel;
    private javax.swing.JLabel shimmerApq3DescriptionLabel;
    private javax.swing.JLabel shimmerApq3ValueLabel;
    private javax.swing.JLabel shimmerApq5DescriptionLabel;
    private javax.swing.JLabel shimmerApq5ValueLabel;
    private javax.swing.JLabel shimmerDdaDescriptionLabel;
    private javax.swing.JLabel shimmerDdaValueLabel;
    private javax.swing.JLabel shimmerLocDbDescriptionLabel;
    private javax.swing.JLabel shimmerLocDbValueLabel;
    private javax.swing.JLabel shimmerLocDescriptionLabel;
    private javax.swing.JLabel shimmerLocValueLabel;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JLabel stdevDescriptionLabel;
    private javax.swing.JLabel stdevValueLabel;
    // End of variables declaration//GEN-END:variables
}
