/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feec.cz.brno.speechproc.gui.parameters.formants;

import au.com.bytecode.opencsv.CSVReader;
import com.google.common.primitives.Doubles;
import feec.cz.brno.speechproc.calc.speechparams.formants.IFormants;
import feec.cz.brno.speechproc.calc.utility.CalcUtilities;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.parameters.results.GraphWindow;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.math3.stat.descriptive.rank.Percentile;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author hynstm
 */
public class FormantsResultPanel extends javax.swing.JPanel {
    
    private final static Logger logger = LogManager.getLogger(FormantsResultPanel.class);

    private File csvResultFile;
    private DefaultTableModel formantTableModel;
    
    private final File sourceSoundFile;
    private GraphWindow formantsGraph;
    
    /**
     * Creates new form FormantsResultPanel
     * @param sourceSoundFile
     * @param csvResultFile
     */
    public FormantsResultPanel(File sourceSoundFile, File csvResultFile) {
        this.sourceSoundFile = sourceSoundFile;
        this.csvResultFile = csvResultFile;
        initComponents();
        loadFormantsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        formantTableModel = new DefaultTableModel();
        formantsTable = new javax.swing.JTable(formantTableModel);
        infoPanel = new javax.swing.JPanel();
        formant2Panel = new javax.swing.JPanel();
        meanDescriptionF2Label = new javax.swing.JLabel();
        meanF2Label = new javax.swing.JLabel();
        medianDescriptionF2Label = new javax.swing.JLabel();
        medianF2Label = new javax.swing.JLabel();
        stedvF2DescriptionLabel = new javax.swing.JLabel();
        stdevF2ValueLabel = new javax.swing.JLabel();
        minF2DescriptionLabel = new javax.swing.JLabel();
        minF2ValueLabel = new javax.swing.JLabel();
        maxF2DescriptionLabel = new javax.swing.JLabel();
        maxF2ValueLabel = new javax.swing.JLabel();
        varianceF2DescriptionLabel = new javax.swing.JLabel();
        varianceF2ValueLabel = new javax.swing.JLabel();
        firstPerF2DescriptionLabel = new javax.swing.JLabel();
        firstPerF2ValueLabel = new javax.swing.JLabel();
        ninePerF2DescriptionLabel = new javax.swing.JLabel();
        ninePerF2ValueLabel = new javax.swing.JLabel();
        irF2DescriptionLabel = new javax.swing.JLabel();
        irF2ValueLabel = new javax.swing.JLabel();
        formant3Panel = new javax.swing.JPanel();
        meanDescriptionF3Label = new javax.swing.JLabel();
        meanF3Label = new javax.swing.JLabel();
        medianDescriptionF3Label = new javax.swing.JLabel();
        medianF3Label = new javax.swing.JLabel();
        stdevF3DescriptionLabel = new javax.swing.JLabel();
        stdevF3ValueLabel = new javax.swing.JLabel();
        minF3DescriptionLabel = new javax.swing.JLabel();
        minF3ValueLabel = new javax.swing.JLabel();
        maxF3DescriptionLabel = new javax.swing.JLabel();
        maxF3ValueLabel = new javax.swing.JLabel();
        varianceF3DescriptionLabel = new javax.swing.JLabel();
        varianceF3ValueLabel = new javax.swing.JLabel();
        firstPerF3DescriptionLabel = new javax.swing.JLabel();
        firstPerF3ValueLabel = new javax.swing.JLabel();
        ninePerF3DescriptionLabel = new javax.swing.JLabel();
        ninePerF3ValueLabel = new javax.swing.JLabel();
        irF3DescriptionLabel = new javax.swing.JLabel();
        irF3ValueLabel = new javax.swing.JLabel();
        showGraphButton = new javax.swing.JButton(Icons.GRAPH_ICON);
        formant1Panel = new javax.swing.JPanel();
        meanDescriptionF1Label = new javax.swing.JLabel();
        meanF1Label = new javax.swing.JLabel();
        medianDescriptionF1Label = new javax.swing.JLabel();
        medianF1Label = new javax.swing.JLabel();
        stdevF1DescriptionLabel = new javax.swing.JLabel();
        stdevF1ValueLabel = new javax.swing.JLabel();
        minF1DescriptionLabel = new javax.swing.JLabel();
        minF1ValueLabel = new javax.swing.JLabel();
        maxF1DescriptionLabel = new javax.swing.JLabel();
        maxF1ValueLabel = new javax.swing.JLabel();
        varianceF1DescriptionLabel = new javax.swing.JLabel();
        varianceF1ValueLabel = new javax.swing.JLabel();
        firstPerF1DescriptionLabel = new javax.swing.JLabel();
        firstPerF1ValueLabel = new javax.swing.JLabel();
        ninePerF1DescriptionLabel = new javax.swing.JLabel();
        ninePerF1ValueLabel = new javax.swing.JLabel();
        irF1DescriptionLabel = new javax.swing.JLabel();
        irF1ValueLabel = new javax.swing.JLabel();
        bandwidth1Panel = new javax.swing.JPanel();
        meanDescriptionB1Label = new javax.swing.JLabel();
        meanB1Label = new javax.swing.JLabel();
        medianDescriptionB1Label = new javax.swing.JLabel();
        medianB1Label = new javax.swing.JLabel();
        stdevB1DescriptionLabel = new javax.swing.JLabel();
        stdevB1ValueLabel = new javax.swing.JLabel();
        minB1DescriptionLabel = new javax.swing.JLabel();
        minB1ValueLabel = new javax.swing.JLabel();
        maxB1DescriptionLabel = new javax.swing.JLabel();
        maxB1ValueLabel = new javax.swing.JLabel();
        varianceB1DescriptionLabel = new javax.swing.JLabel();
        varianceB1ValueLabel = new javax.swing.JLabel();
        firstPerB1DescriptionLabel = new javax.swing.JLabel();
        firstPerB1ValueLabel = new javax.swing.JLabel();
        ninePerB1DescriptionLabel = new javax.swing.JLabel();
        ninePerB1ValueLabel = new javax.swing.JLabel();
        irB1DescriptionLabel = new javax.swing.JLabel();
        irB1ValueLabel = new javax.swing.JLabel();
        bandwidth2Panel = new javax.swing.JPanel();
        meanDescriptionB2Label = new javax.swing.JLabel();
        meanB2Label = new javax.swing.JLabel();
        medianDescriptionB2Label = new javax.swing.JLabel();
        medianB2Label = new javax.swing.JLabel();
        stdevB2DescriptionLabel = new javax.swing.JLabel();
        stdevB2ValueLabel = new javax.swing.JLabel();
        minB2DescriptionLabel = new javax.swing.JLabel();
        minB2ValueLabel = new javax.swing.JLabel();
        maxB2DescriptionLabel = new javax.swing.JLabel();
        maxB2ValueLabel = new javax.swing.JLabel();
        varianceB2DescriptionLabel = new javax.swing.JLabel();
        varianceB2ValueLabel = new javax.swing.JLabel();
        firstPerB2DescriptionLabel = new javax.swing.JLabel();
        firstPerB2ValueLabel = new javax.swing.JLabel();
        ninePerB2DescriptionLabel = new javax.swing.JLabel();
        ninePerB2ValueLabel = new javax.swing.JLabel();
        irB2DescriptionLabel = new javax.swing.JLabel();
        irB2ValueLabel = new javax.swing.JLabel();
        bandwidth3Panel = new javax.swing.JPanel();
        meanDescriptionB3Label = new javax.swing.JLabel();
        meanB3Label = new javax.swing.JLabel();
        medianDescriptionB3Label = new javax.swing.JLabel();
        medianB3Label = new javax.swing.JLabel();
        stdevB3DescriptionLabel = new javax.swing.JLabel();
        stdevB3ValueLabel = new javax.swing.JLabel();
        minB3DescriptionLabel = new javax.swing.JLabel();
        minB3ValueLabel = new javax.swing.JLabel();
        maxB3DescriptionLabel = new javax.swing.JLabel();
        maxB3ValueLabel = new javax.swing.JLabel();
        varianceB3DescriptionLabel = new javax.swing.JLabel();
        varianceB3ValueLabel = new javax.swing.JLabel();
        firstPerB3DescriptionLabel = new javax.swing.JLabel();
        firstPerB3ValueLabel = new javax.swing.JLabel();
        ninePerB3DescriptionLabel = new javax.swing.JLabel();
        ninePerB3ValueLabel = new javax.swing.JLabel();
        irB3DescriptionLabel = new javax.swing.JLabel();
        irB3ValueLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        formantsTable.setModel(formantTableModel);
        tableScrollPane.setViewportView(formantsTable);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);

        formant2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 2"));

        meanDescriptionF2Label.setText("Mean:");

        meanF2Label.setText("jLabel7");

        medianDescriptionF2Label.setText("Median:");

        medianF2Label.setText("jLabel7");

        stedvF2DescriptionLabel.setText("Stdev");

        stdevF2ValueLabel.setText("jLabel1");

        minF2DescriptionLabel.setText("Min:");

        minF2ValueLabel.setText("jLabel1");

        maxF2DescriptionLabel.setText("Max:");

        maxF2ValueLabel.setText("jLabel2");

        varianceF2DescriptionLabel.setText("Variance:");

        varianceF2ValueLabel.setText("jLabel2");

        firstPerF2DescriptionLabel.setText("1.p:");
        firstPerF2DescriptionLabel.setToolTipText("1.percentil");

        firstPerF2ValueLabel.setText("jLabel2");

        ninePerF2DescriptionLabel.setText("99.p:");
        ninePerF2DescriptionLabel.setToolTipText("99. percentil");

        ninePerF2ValueLabel.setText("jLabel4");

        irF2DescriptionLabel.setText("IR:");

        irF2ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant2PanelLayout = new javax.swing.GroupLayout(formant2Panel);
        formant2Panel.setLayout(formant2PanelLayout);
        formant2PanelLayout.setHorizontalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianDescriptionF2Label)
                    .addComponent(meanDescriptionF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stedvF2DescriptionLabel)
                    .addComponent(minF2DescriptionLabel)
                    .addComponent(maxF2DescriptionLabel)
                    .addComponent(varianceF2DescriptionLabel)
                    .addComponent(firstPerF2DescriptionLabel)
                    .addComponent(ninePerF2DescriptionLabel)
                    .addComponent(irF2DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(medianF2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdevF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formant2PanelLayout.createSequentialGroup()
                        .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstPerF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(ninePerF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(irF2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant2PanelLayout.setVerticalGroup(
            formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanDescriptionF2Label)
                    .addComponent(meanF2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianF2Label)
                    .addComponent(medianDescriptionF2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stedvF2DescriptionLabel)
                    .addComponent(stdevF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceF2DescriptionLabel)
                    .addComponent(varianceF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF2DescriptionLabel)
                    .addComponent(minF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxF2DescriptionLabel)
                    .addComponent(maxF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF2DescriptionLabel)
                    .addComponent(firstPerF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF2DescriptionLabel)
                    .addComponent(ninePerF2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formant2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(irF2DescriptionLabel)
                    .addComponent(irF2ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        formant3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 3"));

        meanDescriptionF3Label.setText("Mean:");

        meanF3Label.setText("jLabel8");

        medianDescriptionF3Label.setText("Median:");

        medianF3Label.setText("jLabel9");

        stdevF3DescriptionLabel.setText("Stdev:");

        stdevF3ValueLabel.setText("jLabel2");

        minF3DescriptionLabel.setText("Min:");

        minF3ValueLabel.setText("jLabel2");

        maxF3DescriptionLabel.setText("Max:");

        maxF3ValueLabel.setText("jLabel2");

        varianceF3DescriptionLabel.setText("Variance:");

        varianceF3ValueLabel.setText("jLabel2");

        firstPerF3DescriptionLabel.setText("1.p:");
        firstPerF3DescriptionLabel.setToolTipText("1.percentil");

        firstPerF3ValueLabel.setText("jLabel2");

        ninePerF3DescriptionLabel.setText("99.p:");
        ninePerF3DescriptionLabel.setToolTipText("99. percentil");

        ninePerF3ValueLabel.setText("jLabel4");

        irF3DescriptionLabel.setText("IR:");

        irF3ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant3PanelLayout = new javax.swing.GroupLayout(formant3Panel);
        formant3Panel.setLayout(formant3PanelLayout);
        formant3PanelLayout.setHorizontalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionF3Label)
                    .addComponent(stdevF3DescriptionLabel)
                    .addComponent(minF3DescriptionLabel)
                    .addComponent(maxF3DescriptionLabel)
                    .addComponent(varianceF3DescriptionLabel)
                    .addComponent(firstPerF3DescriptionLabel)
                    .addComponent(ninePerF3DescriptionLabel)
                    .addComponent(irF3DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdevF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerF3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant3PanelLayout.setVerticalGroup(
            formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionF3Label)
                    .addComponent(meanF3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionF3Label)
                    .addComponent(medianF3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevF3DescriptionLabel)
                    .addComponent(stdevF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceF3DescriptionLabel)
                    .addComponent(varianceF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF3DescriptionLabel)
                    .addComponent(minF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxF3DescriptionLabel)
                    .addComponent(maxF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF3DescriptionLabel)
                    .addComponent(firstPerF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF3DescriptionLabel)
                    .addComponent(ninePerF3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irF3DescriptionLabel)
                    .addComponent(irF3ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showGraphButton.setText("Show chart");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        formant1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formant 1"));
        formant1Panel.setToolTipText("");

        meanDescriptionF1Label.setText("Mean: ");

        meanF1Label.setText("jLabel2");

        medianDescriptionF1Label.setText("Median:");

        medianF1Label.setText("jLabel3");

        stdevF1DescriptionLabel.setText("Stdev:");

        stdevF1ValueLabel.setText("jLabel2");

        minF1DescriptionLabel.setText("Min:");

        minF1ValueLabel.setText("jLabel1");

        maxF1DescriptionLabel.setText("Max:");

        maxF1ValueLabel.setText("jLabel1");

        varianceF1DescriptionLabel.setText("Variance:");

        varianceF1ValueLabel.setText("jLabel1");

        firstPerF1DescriptionLabel.setText("1.p:");
        firstPerF1DescriptionLabel.setToolTipText("1.percentil");

        firstPerF1ValueLabel.setText("jLabel2");

        ninePerF1DescriptionLabel.setText("99.p:");
        ninePerF1DescriptionLabel.setToolTipText("99. percentil");

        ninePerF1ValueLabel.setText("jLabel2");

        irF1DescriptionLabel.setText("IR:");

        irF1ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout formant1PanelLayout = new javax.swing.GroupLayout(formant1Panel);
        formant1Panel.setLayout(formant1PanelLayout);
        formant1PanelLayout.setHorizontalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdevF1DescriptionLabel)
                    .addComponent(meanDescriptionF1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varianceF1DescriptionLabel)
                    .addComponent(minF1DescriptionLabel)
                    .addComponent(maxF1DescriptionLabel)
                    .addComponent(firstPerF1DescriptionLabel)
                    .addComponent(ninePerF1DescriptionLabel)
                    .addComponent(irF1DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanF1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdevF1ValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minF1ValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formant1PanelLayout.setVerticalGroup(
            formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formant1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meanF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanDescriptionF1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medianDescriptionF1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianF1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stdevF1DescriptionLabel)
                    .addComponent(stdevF1ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(varianceF1DescriptionLabel)
                    .addComponent(varianceF1ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minF1DescriptionLabel)
                    .addComponent(minF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maxF1DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxF1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerF1DescriptionLabel)
                    .addComponent(firstPerF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerF1DescriptionLabel)
                    .addComponent(ninePerF1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formant1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irF1DescriptionLabel)
                    .addComponent(irF1ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bandwidth1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandwidth 1"));

        meanDescriptionB1Label.setText("Mean:");

        meanB1Label.setText("jLabel8");

        medianDescriptionB1Label.setText("Median:");

        medianB1Label.setText("jLabel9");

        stdevB1DescriptionLabel.setText("Stdev:");

        stdevB1ValueLabel.setText("jLabel2");

        minB1DescriptionLabel.setText("Min:");

        minB1ValueLabel.setText("jLabel2");

        maxB1DescriptionLabel.setText("Max:");

        maxB1ValueLabel.setText("jLabel2");

        varianceB1DescriptionLabel.setText("Variance:");

        varianceB1ValueLabel.setText("jLabel2");

        firstPerB1DescriptionLabel.setText("1.p:");
        firstPerB1DescriptionLabel.setToolTipText("1.percentil");

        firstPerB1ValueLabel.setText("jLabel2");

        ninePerB1DescriptionLabel.setText("99.p:");
        ninePerB1DescriptionLabel.setToolTipText("99. percentil");

        ninePerB1ValueLabel.setText("jLabel4");

        irB1DescriptionLabel.setText("IR:");

        irB1ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout bandwidth1PanelLayout = new javax.swing.GroupLayout(bandwidth1Panel);
        bandwidth1Panel.setLayout(bandwidth1PanelLayout);
        bandwidth1PanelLayout.setHorizontalGroup(
            bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionB1Label)
                    .addComponent(stdevB1DescriptionLabel)
                    .addComponent(minB1DescriptionLabel)
                    .addComponent(maxB1DescriptionLabel)
                    .addComponent(varianceB1DescriptionLabel)
                    .addComponent(firstPerB1DescriptionLabel)
                    .addComponent(ninePerB1DescriptionLabel)
                    .addComponent(irB1DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdevB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianB1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanB1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerB1ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bandwidth1PanelLayout.setVerticalGroup(
            bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB1Label)
                    .addComponent(meanB1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionB1Label)
                    .addComponent(medianB1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevB1DescriptionLabel)
                    .addComponent(stdevB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceB1DescriptionLabel)
                    .addComponent(varianceB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minB1DescriptionLabel)
                    .addComponent(minB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxB1DescriptionLabel)
                    .addComponent(maxB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerB1DescriptionLabel)
                    .addComponent(firstPerB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerB1DescriptionLabel)
                    .addComponent(ninePerB1ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irB1DescriptionLabel)
                    .addComponent(irB1ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bandwidth2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandwidth 2"));

        meanDescriptionB2Label.setText("Mean:");

        meanB2Label.setText("jLabel8");

        medianDescriptionB2Label.setText("Median:");

        medianB2Label.setText("jLabel9");

        stdevB2DescriptionLabel.setText("Stdev:");

        stdevB2ValueLabel.setText("jLabel2");

        minB2DescriptionLabel.setText("Min:");

        minB2ValueLabel.setText("jLabel2");

        maxB2DescriptionLabel.setText("Max:");

        maxB2ValueLabel.setText("jLabel2");

        varianceB2DescriptionLabel.setText("Variance:");

        varianceB2ValueLabel.setText("jLabel2");

        firstPerB2DescriptionLabel.setText("1.p:");
        firstPerB2DescriptionLabel.setToolTipText("1.percentil");

        firstPerB2ValueLabel.setText("jLabel2");

        ninePerB2DescriptionLabel.setText("99.p:");
        ninePerB2DescriptionLabel.setToolTipText("99. percentil");

        ninePerB2ValueLabel.setText("jLabel4");

        irB2DescriptionLabel.setText("IR:");

        irB2ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout bandwidth2PanelLayout = new javax.swing.GroupLayout(bandwidth2Panel);
        bandwidth2Panel.setLayout(bandwidth2PanelLayout);
        bandwidth2PanelLayout.setHorizontalGroup(
            bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionB2Label)
                    .addComponent(stdevB2DescriptionLabel)
                    .addComponent(minB2DescriptionLabel)
                    .addComponent(maxB2DescriptionLabel)
                    .addComponent(varianceB2DescriptionLabel)
                    .addComponent(firstPerB2DescriptionLabel)
                    .addComponent(ninePerB2DescriptionLabel)
                    .addComponent(irB2DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdevB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianB2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanB2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerB2ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bandwidth2PanelLayout.setVerticalGroup(
            bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB2Label)
                    .addComponent(meanB2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionB2Label)
                    .addComponent(medianB2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevB2DescriptionLabel)
                    .addComponent(stdevB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceB2DescriptionLabel)
                    .addComponent(varianceB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minB2DescriptionLabel)
                    .addComponent(minB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxB2DescriptionLabel)
                    .addComponent(maxB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerB2DescriptionLabel)
                    .addComponent(firstPerB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerB2DescriptionLabel)
                    .addComponent(ninePerB2ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irB2DescriptionLabel)
                    .addComponent(irB2ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bandwidth3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandwidth 3"));

        meanDescriptionB3Label.setText("Mean:");

        meanB3Label.setText("jLabel8");

        medianDescriptionB3Label.setText("Median:");

        medianB3Label.setText("jLabel9");

        stdevB3DescriptionLabel.setText("Stdev:");

        stdevB3ValueLabel.setText("jLabel2");

        minB3DescriptionLabel.setText("Min:");

        minB3ValueLabel.setText("jLabel2");

        maxB3DescriptionLabel.setText("Max:");

        maxB3ValueLabel.setText("jLabel2");

        varianceB3DescriptionLabel.setText("Variance:");

        varianceB3ValueLabel.setText("jLabel2");

        firstPerB3DescriptionLabel.setText("1.p:");
        firstPerB3DescriptionLabel.setToolTipText("1.percentil");

        firstPerB3ValueLabel.setText("jLabel2");

        ninePerB3DescriptionLabel.setText("99.p:");
        ninePerB3DescriptionLabel.setToolTipText("99. percentil");

        ninePerB3ValueLabel.setText("jLabel4");

        irB3DescriptionLabel.setText("IR:");

        irB3ValueLabel.setText("jLabel2");

        javax.swing.GroupLayout bandwidth3PanelLayout = new javax.swing.GroupLayout(bandwidth3Panel);
        bandwidth3Panel.setLayout(bandwidth3PanelLayout);
        bandwidth3PanelLayout.setHorizontalGroup(
            bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianDescriptionB3Label)
                    .addComponent(stdevB3DescriptionLabel)
                    .addComponent(minB3DescriptionLabel)
                    .addComponent(maxB3DescriptionLabel)
                    .addComponent(varianceB3DescriptionLabel)
                    .addComponent(firstPerB3DescriptionLabel)
                    .addComponent(ninePerB3DescriptionLabel)
                    .addComponent(irB3DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdevB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medianB3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(meanB3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varianceB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPerB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ninePerB3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bandwidth3PanelLayout.setVerticalGroup(
            bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandwidth3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meanDescriptionB3Label)
                    .addComponent(meanB3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionB3Label)
                    .addComponent(medianB3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevB3DescriptionLabel)
                    .addComponent(stdevB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianceB3DescriptionLabel)
                    .addComponent(varianceB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minB3DescriptionLabel)
                    .addComponent(minB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxB3DescriptionLabel)
                    .addComponent(maxB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPerB3DescriptionLabel)
                    .addComponent(firstPerB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninePerB3DescriptionLabel)
                    .addComponent(ninePerB3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bandwidth3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irB3DescriptionLabel)
                    .addComponent(irB3ValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formant1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formant3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandwidth1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandwidth2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandwidth3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showGraphButton)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formant1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bandwidth2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bandwidth1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bandwidth3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(formant2Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formant3Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(showGraphButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(infoPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        logger.debug("Showing formants chart from " + csvResultFile.getName());
        if (formantsGraph == null) {
            FormantCharts graph = new FormantCharts();
            formantsGraph = new GraphWindow(csvResultFile.getAbsolutePath(), graph.createChart(csvResultFile));
            formantsGraph.setVisible(true);
        } else {
            formantsGraph.setVisible(true);
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void loadFormantsTable() {
        String[] csvLine;
        List<Double> formant1 = new ArrayList<>();
        List<Double> formant2 = new ArrayList<>();
        List<Double> formant3 = new ArrayList<>();
        List<Double> bandwidth1 = new ArrayList<>();
        List<Double> bandwidth2 = new ArrayList<>();
        List<Double> bandwidth3 = new ArrayList<>();
        CSVReader reader = null;
        try {
            reader = new CSVReader(new FileReader(csvResultFile));
            String[] header = reader.readNext();
            formantTableModel.setColumnIdentifiers(header);
            while ((csvLine = reader.readNext()) != null) {
                formantTableModel.addRow(csvLine);
                try { formant1.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_1])); } catch (NumberFormatException e) {}
                try { formant2.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_2])); } catch (NumberFormatException e) {}
                try { formant3.add(Double.parseDouble(csvLine[IFormants.COLUMN_FORMANT_3])); } catch (NumberFormatException e) {}
                try { bandwidth1.add(Double.parseDouble(csvLine[IFormants.COLUMN_BANDWIDTH_1])); } catch (NumberFormatException e) {}
                try { bandwidth2.add(Double.parseDouble(csvLine[IFormants.COLUMN_BANDWIDTH_2])); } catch (NumberFormatException e) {}
                try { bandwidth3.add(Double.parseDouble(csvLine[IFormants.COLUMN_BANDWIDTH_3])); } catch (NumberFormatException e) {}
            }
            reader.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load formants table from CSV file!", "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load formants table from CSV file!", ex);
        }
        formantsTable.setModel(formantTableModel);
        formantTableModel.fireTableDataChanged();
   
        // FORMANTS
        meanF1Label.setText(CalcUtilities.mean(formant1) + " Hz");
        meanF2Label.setText(CalcUtilities.mean(formant2) + " Hz");
        meanF3Label.setText(CalcUtilities.mean(formant3) + " Hz");

        medianF1Label.setText(CalcUtilities.median(formant1) + " Hz");
        medianF2Label.setText(CalcUtilities.median(formant2) + " Hz");
        medianF3Label.setText(CalcUtilities.median(formant3) + " Hz");
        
        stdevF1ValueLabel.setText(CalcUtilities.stdev(formant1) + " Hz");
        stdevF2ValueLabel.setText(CalcUtilities.stdev(formant2) + " Hz");
        stdevF3ValueLabel.setText(CalcUtilities.stdev(formant3) + " Hz");
        
        varianceF1ValueLabel.setText(CalcUtilities.variance(formant1) + " Hz");
        varianceF2ValueLabel.setText(CalcUtilities.variance(formant2) + " Hz");
        varianceF3ValueLabel.setText(CalcUtilities.variance(formant3) + " Hz");
        
        minF1ValueLabel.setText(Collections.min(formant1) + " Hz");
        minF2ValueLabel.setText(Collections.min(formant2) + " Hz");
        minF3ValueLabel.setText(Collections.min(formant3) + " Hz");
        
        maxF1ValueLabel.setText(Collections.max(formant1) + " Hz");
        maxF2ValueLabel.setText(Collections.max(formant2) + " Hz");
        maxF3ValueLabel.setText(Collections.max(formant3) + " Hz");
        
        Percentile percentile = new Percentile(0.1);
        double firstPerF1 = percentile.evaluate(Doubles.toArray(formant1));
        double firstPerF2 = percentile.evaluate(Doubles.toArray(formant2));
        double firstPerF3 = percentile.evaluate(Doubles.toArray(formant3));
        firstPerF1ValueLabel.setText(firstPerF1 + " Hz");
        firstPerF2ValueLabel.setText(firstPerF2 + " Hz");
        firstPerF3ValueLabel.setText(firstPerF3 + " Hz");
        
        percentile = new Percentile(0.99);
        double ninePerF1 = percentile.evaluate(Doubles.toArray(formant1));
        double ninePerF2 = percentile.evaluate(Doubles.toArray(formant2));
        double ninePerF3 = percentile.evaluate(Doubles.toArray(formant3));
        ninePerF1ValueLabel.setText(ninePerF1 + " Hz");
        ninePerF2ValueLabel.setText(ninePerF2 + " Hz");
        ninePerF3ValueLabel.setText(ninePerF3 + " Hz");
        
        irF1ValueLabel.setText(ninePerF1 - firstPerF1 + " Hz");
        irF2ValueLabel.setText(ninePerF2 - firstPerF2 + " Hz");
        irF3ValueLabel.setText(ninePerF3 - firstPerF3 + " Hz");
        
        // BANDWIDTH
        meanB1Label.setText(CalcUtilities.mean(bandwidth1) + " Hz");
        meanB2Label.setText(CalcUtilities.mean(bandwidth2) + " Hz");
        meanB3Label.setText(CalcUtilities.mean(bandwidth3) + " Hz");

        medianB1Label.setText(CalcUtilities.median(bandwidth1) + " Hz");
        medianB2Label.setText(CalcUtilities.median(bandwidth2) + " Hz");
        medianB3Label.setText(CalcUtilities.median(bandwidth3) + " Hz");

        stdevB1ValueLabel.setText(CalcUtilities.stdev(bandwidth1) + " Hz");
        stdevB2ValueLabel.setText(CalcUtilities.stdev(bandwidth2) + " Hz");
        stdevB3ValueLabel.setText(CalcUtilities.stdev(bandwidth3) + " Hz");

        varianceB1ValueLabel.setText(CalcUtilities.variance(bandwidth1) + " Hz");
        varianceB2ValueLabel.setText(CalcUtilities.variance(bandwidth2) + " Hz");
        varianceB3ValueLabel.setText(CalcUtilities.variance(bandwidth3) + " Hz");

        minB1ValueLabel.setText(Collections.min(bandwidth1) + " Hz");
        minB2ValueLabel.setText(Collections.min(bandwidth2) + " Hz");
        minB3ValueLabel.setText(Collections.min(bandwidth3) + " Hz");

        maxB1ValueLabel.setText(Collections.max(bandwidth1) + " Hz");
        maxB2ValueLabel.setText(Collections.max(bandwidth2) + " Hz");
        maxB3ValueLabel.setText(Collections.max(bandwidth3) + " Hz");

        percentile = new Percentile(0.1);
        firstPerF1 = percentile.evaluate(Doubles.toArray(bandwidth1));
        firstPerF2 = percentile.evaluate(Doubles.toArray(bandwidth2));
        firstPerF3 = percentile.evaluate(Doubles.toArray(bandwidth3));
        firstPerB1ValueLabel.setText(firstPerF1 + " Hz");
        firstPerB2ValueLabel.setText(firstPerF2 + " Hz");
        firstPerB3ValueLabel.setText(firstPerF3 + " Hz");

        percentile = new Percentile(0.99);
        ninePerF1 = percentile.evaluate(Doubles.toArray(bandwidth1));
        ninePerF2 = percentile.evaluate(Doubles.toArray(bandwidth2));
        ninePerF3 = percentile.evaluate(Doubles.toArray(bandwidth3));
        ninePerB1ValueLabel.setText(ninePerF1 + " Hz");
        ninePerB2ValueLabel.setText(ninePerF2 + " Hz");
        ninePerB3ValueLabel.setText(ninePerF3 + " Hz");

        irB1ValueLabel.setText(ninePerF1 - firstPerF1 + " Hz");
        irB2ValueLabel.setText(ninePerF2 - firstPerF2 + " Hz");
        irB3ValueLabel.setText(ninePerF3 - firstPerF3 + " Hz");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bandwidth1Panel;
    private javax.swing.JPanel bandwidth2Panel;
    private javax.swing.JPanel bandwidth3Panel;
    private javax.swing.JLabel firstPerB1DescriptionLabel;
    private javax.swing.JLabel firstPerB1ValueLabel;
    private javax.swing.JLabel firstPerB2DescriptionLabel;
    private javax.swing.JLabel firstPerB2ValueLabel;
    private javax.swing.JLabel firstPerB3DescriptionLabel;
    private javax.swing.JLabel firstPerB3ValueLabel;
    private javax.swing.JLabel firstPerF1DescriptionLabel;
    private javax.swing.JLabel firstPerF1ValueLabel;
    private javax.swing.JLabel firstPerF2DescriptionLabel;
    private javax.swing.JLabel firstPerF2ValueLabel;
    private javax.swing.JLabel firstPerF3DescriptionLabel;
    private javax.swing.JLabel firstPerF3ValueLabel;
    private javax.swing.JPanel formant1Panel;
    private javax.swing.JPanel formant2Panel;
    private javax.swing.JPanel formant3Panel;
    private javax.swing.JTable formantsTable;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel irB1DescriptionLabel;
    private javax.swing.JLabel irB1ValueLabel;
    private javax.swing.JLabel irB2DescriptionLabel;
    private javax.swing.JLabel irB2ValueLabel;
    private javax.swing.JLabel irB3DescriptionLabel;
    private javax.swing.JLabel irB3ValueLabel;
    private javax.swing.JLabel irF1DescriptionLabel;
    private javax.swing.JLabel irF1ValueLabel;
    private javax.swing.JLabel irF2DescriptionLabel;
    private javax.swing.JLabel irF2ValueLabel;
    private javax.swing.JLabel irF3DescriptionLabel;
    private javax.swing.JLabel irF3ValueLabel;
    private javax.swing.JLabel maxB1DescriptionLabel;
    private javax.swing.JLabel maxB1ValueLabel;
    private javax.swing.JLabel maxB2DescriptionLabel;
    private javax.swing.JLabel maxB2ValueLabel;
    private javax.swing.JLabel maxB3DescriptionLabel;
    private javax.swing.JLabel maxB3ValueLabel;
    private javax.swing.JLabel maxF1DescriptionLabel;
    private javax.swing.JLabel maxF1ValueLabel;
    private javax.swing.JLabel maxF2DescriptionLabel;
    private javax.swing.JLabel maxF2ValueLabel;
    private javax.swing.JLabel maxF3DescriptionLabel;
    private javax.swing.JLabel maxF3ValueLabel;
    private javax.swing.JLabel meanB1Label;
    private javax.swing.JLabel meanB2Label;
    private javax.swing.JLabel meanB3Label;
    private javax.swing.JLabel meanDescriptionB1Label;
    private javax.swing.JLabel meanDescriptionB2Label;
    private javax.swing.JLabel meanDescriptionB3Label;
    private javax.swing.JLabel meanDescriptionF1Label;
    private javax.swing.JLabel meanDescriptionF2Label;
    private javax.swing.JLabel meanDescriptionF3Label;
    private javax.swing.JLabel meanF1Label;
    private javax.swing.JLabel meanF2Label;
    private javax.swing.JLabel meanF3Label;
    private javax.swing.JLabel medianB1Label;
    private javax.swing.JLabel medianB2Label;
    private javax.swing.JLabel medianB3Label;
    private javax.swing.JLabel medianDescriptionB1Label;
    private javax.swing.JLabel medianDescriptionB2Label;
    private javax.swing.JLabel medianDescriptionB3Label;
    private javax.swing.JLabel medianDescriptionF1Label;
    private javax.swing.JLabel medianDescriptionF2Label;
    private javax.swing.JLabel medianDescriptionF3Label;
    private javax.swing.JLabel medianF1Label;
    private javax.swing.JLabel medianF2Label;
    private javax.swing.JLabel medianF3Label;
    private javax.swing.JLabel minB1DescriptionLabel;
    private javax.swing.JLabel minB1ValueLabel;
    private javax.swing.JLabel minB2DescriptionLabel;
    private javax.swing.JLabel minB2ValueLabel;
    private javax.swing.JLabel minB3DescriptionLabel;
    private javax.swing.JLabel minB3ValueLabel;
    private javax.swing.JLabel minF1DescriptionLabel;
    private javax.swing.JLabel minF1ValueLabel;
    private javax.swing.JLabel minF2DescriptionLabel;
    private javax.swing.JLabel minF2ValueLabel;
    private javax.swing.JLabel minF3DescriptionLabel;
    private javax.swing.JLabel minF3ValueLabel;
    private javax.swing.JLabel ninePerB1DescriptionLabel;
    private javax.swing.JLabel ninePerB1ValueLabel;
    private javax.swing.JLabel ninePerB2DescriptionLabel;
    private javax.swing.JLabel ninePerB2ValueLabel;
    private javax.swing.JLabel ninePerB3DescriptionLabel;
    private javax.swing.JLabel ninePerB3ValueLabel;
    private javax.swing.JLabel ninePerF1DescriptionLabel;
    private javax.swing.JLabel ninePerF1ValueLabel;
    private javax.swing.JLabel ninePerF2DescriptionLabel;
    private javax.swing.JLabel ninePerF2ValueLabel;
    private javax.swing.JLabel ninePerF3DescriptionLabel;
    private javax.swing.JLabel ninePerF3ValueLabel;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JLabel stdevB1DescriptionLabel;
    private javax.swing.JLabel stdevB1ValueLabel;
    private javax.swing.JLabel stdevB2DescriptionLabel;
    private javax.swing.JLabel stdevB2ValueLabel;
    private javax.swing.JLabel stdevB3DescriptionLabel;
    private javax.swing.JLabel stdevB3ValueLabel;
    private javax.swing.JLabel stdevF1DescriptionLabel;
    private javax.swing.JLabel stdevF1ValueLabel;
    private javax.swing.JLabel stdevF2ValueLabel;
    private javax.swing.JLabel stdevF3DescriptionLabel;
    private javax.swing.JLabel stdevF3ValueLabel;
    private javax.swing.JLabel stedvF2DescriptionLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel varianceB1DescriptionLabel;
    private javax.swing.JLabel varianceB1ValueLabel;
    private javax.swing.JLabel varianceB2DescriptionLabel;
    private javax.swing.JLabel varianceB2ValueLabel;
    private javax.swing.JLabel varianceB3DescriptionLabel;
    private javax.swing.JLabel varianceB3ValueLabel;
    private javax.swing.JLabel varianceF1DescriptionLabel;
    private javax.swing.JLabel varianceF1ValueLabel;
    private javax.swing.JLabel varianceF2DescriptionLabel;
    private javax.swing.JLabel varianceF2ValueLabel;
    private javax.swing.JLabel varianceF3DescriptionLabel;
    private javax.swing.JLabel varianceF3ValueLabel;
    // End of variables declaration//GEN-END:variables
}
