/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feec.cz.brno.speechproc.gui.parameters.f0;

import au.com.bytecode.opencsv.CSVReader;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.parameters.results.GraphWindow;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author mira
 */
public class F0ResultPanel extends javax.swing.JPanel {
    
    private final static Logger logger = LogManager.getLogger(F0ResultPanel.class);
    
    private final DefaultTableModel f0TableModel = new DefaultTableModel();
    
    private final File csvResultFile;
    private final File csvStatsFile;
    private final File sourceSoundFile;
    
    private GraphWindow f0Graph;

    /**
     * Creates new form F0ResultPanel
     * @param sourceSoundFile
     * @param csvResultFile
     * @param csvStatsFile
     */
    public F0ResultPanel(File sourceSoundFile, File csvResultFile, File csvStatsFile) {
        this.csvResultFile = csvResultFile;
        this.csvStatsFile = csvStatsFile;
        this.sourceSoundFile = sourceSoundFile;
        initComponents();
        loadF0Table();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        showGraphButton = new javax.swing.JButton(Icons.GRAPH_ICON);
        jPanel2 = new javax.swing.JPanel();
        meanDescriptionLabel = new javax.swing.JLabel();
        medianDescriptionLabel = new javax.swing.JLabel();
        medianValuleLabel = new javax.swing.JLabel();
        meanValueLabel = new javax.swing.JLabel();
        stdevDescriptionLabel = new javax.swing.JLabel();
        stdevValueLabel = new javax.swing.JLabel();
        minDescriptionLabel = new javax.swing.JLabel();
        minValueLabel = new javax.swing.JLabel();
        maxDescriptionLabel = new javax.swing.JLabel();
        maxValueLabel = new javax.swing.JLabel();
        varDescriptionLabel = new javax.swing.JLabel();
        varValueLabel = new javax.swing.JLabel();
        vrDescriptionLabel = new javax.swing.JLabel();
        vrValueLabel = new javax.swing.JLabel();
        relVRDescriptionLabel = new javax.swing.JLabel();
        relVRValueLabel = new javax.swing.JLabel();
        relStdevDescriptionLabel = new javax.swing.JLabel();
        relStdevValueLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jitterLocDescriptionLabel = new javax.swing.JLabel();
        jitterLocValueLabel = new javax.swing.JLabel();
        jitterLocAbsDescriptionLabel = new javax.swing.JLabel();
        jitterLocAbsValueLabel = new javax.swing.JLabel();
        jitterRapDescriptionLabel = new javax.swing.JLabel();
        jitterRapValueLabel = new javax.swing.JLabel();
        jitterPpq5DescriptionLabel = new javax.swing.JLabel();
        jitterDdpDescriptionLabel = new javax.swing.JLabel();
        jitterPpq5ValueLabel = new javax.swing.JLabel();
        jitterDdpValueLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        shimmerLocDescriptionLabel = new javax.swing.JLabel();
        shimmerLocValueLabel = new javax.swing.JLabel();
        shimmerLocDbDescriptionLabel = new javax.swing.JLabel();
        shimmerLocDbValueLabel = new javax.swing.JLabel();
        shimmerApq3DescriptionLabel = new javax.swing.JLabel();
        shimmerApq3ValueLabel = new javax.swing.JLabel();
        shimmerApq5DescriptionLabel = new javax.swing.JLabel();
        shimmerApq5ValueLabel = new javax.swing.JLabel();
        shimmerApq11DescriptionLabel = new javax.swing.JLabel();
        shimmerApq11ValueLabel = new javax.swing.JLabel();
        shimmerDdaDescriptionLabel = new javax.swing.JLabel();
        shimmerDdaValueLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        hnrAutDescriptionLabel = new javax.swing.JLabel();
        hnrNHDescriptionLabel = new javax.swing.JLabel();
        hnrHNDescriptionLabel = new javax.swing.JLabel();
        hnrAutValueLabel = new javax.swing.JLabel();
        hnrNHValueLabel = new javax.swing.JLabel();
        hnrHNValueLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        voiceFracDescriptionLabel = new javax.swing.JLabel();
        voiceFracValueLabel = new javax.swing.JLabel();
        voiceNBreaksDescriptionLabel = new javax.swing.JLabel();
        voiceNBreaksValueLabel = new javax.swing.JLabel();
        voiceDegreeDescriptionLabel = new javax.swing.JLabel();
        voiceDegreeValueLabel = new javax.swing.JLabel();
        tptDescriptionLabel = new javax.swing.JLabel();
        tptValueLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        meanEnergyDescriptionLabel = new javax.swing.JLabel();
        meanEnergyValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        f0Table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        showGraphButton.setText("Show chart");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("F0 info"));

        meanDescriptionLabel.setText("F0 mean:");

        medianDescriptionLabel.setText("F0 median:");

        medianValuleLabel.setText("jLabel1");

        meanValueLabel.setText("jLabel1");

        stdevDescriptionLabel.setText("F0 stdev:");

        stdevValueLabel.setText("jLabel1");

        minDescriptionLabel.setText("F0 min:");

        minValueLabel.setText("jLabel1");

        maxDescriptionLabel.setText("F0 max:");

        maxValueLabel.setText("jLabel2");

        varDescriptionLabel.setText("F0 var:");

        varValueLabel.setText("jLabel1");

        vrDescriptionLabel.setText("F0 VR:");

        vrValueLabel.setText("jLabel1");

        relVRDescriptionLabel.setText("rel F0 VR:");

        relVRValueLabel.setText("jLabel1");

        relStdevDescriptionLabel.setText("rel F0 SD:");

        relStdevValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianDescriptionLabel)
                            .addComponent(meanDescriptionLabel))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianValuleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meanValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdevDescriptionLabel)
                            .addComponent(minDescriptionLabel)
                            .addComponent(maxDescriptionLabel)
                            .addComponent(varDescriptionLabel)
                            .addComponent(vrDescriptionLabel)
                            .addComponent(relVRDescriptionLabel))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(minValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stdevValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(varValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(vrValueLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(relVRValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(relStdevDescriptionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(relStdevValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meanDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meanValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianDescriptionLabel)
                    .addComponent(medianValuleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdevDescriptionLabel)
                    .addComponent(stdevValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varDescriptionLabel)
                            .addComponent(varValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minDescriptionLabel))
                    .addComponent(minValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDescriptionLabel)
                    .addComponent(maxValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrDescriptionLabel)
                    .addComponent(vrValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relVRDescriptionLabel)
                    .addComponent(relVRValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relStdevDescriptionLabel)
                    .addComponent(relStdevValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jitter"));

        jitterLocDescriptionLabel.setText("Jitter (local):");

        jitterLocValueLabel.setText("jLabel1");

        jitterLocAbsDescriptionLabel.setText("Jitter (local, absolute):");

        jitterLocAbsValueLabel.setText("jLabel1");

        jitterRapDescriptionLabel.setText("Jitter (rap): ");

        jitterRapValueLabel.setText("jLabel1");

        jitterPpq5DescriptionLabel.setText("Jitter (ppq5):");

        jitterDdpDescriptionLabel.setText("Jitter (ddp):");

        jitterPpq5ValueLabel.setText("jLabel1");

        jitterDdpValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jitterLocAbsDescriptionLabel)
                    .addComponent(jitterRapDescriptionLabel)
                    .addComponent(jitterPpq5DescriptionLabel)
                    .addComponent(jitterDdpDescriptionLabel)
                    .addComponent(jitterLocDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jitterLocAbsValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jitterRapValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterLocValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterPpq5ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jitterDdpValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterLocDescriptionLabel)
                    .addComponent(jitterLocValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterLocAbsDescriptionLabel)
                    .addComponent(jitterLocAbsValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterRapDescriptionLabel)
                    .addComponent(jitterRapValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterPpq5DescriptionLabel)
                    .addComponent(jitterPpq5ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitterDdpDescriptionLabel)
                    .addComponent(jitterDdpValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Shimmer"));

        shimmerLocDescriptionLabel.setText("Shimmer (local):");

        shimmerLocValueLabel.setText("jLabel1");

        shimmerLocDbDescriptionLabel.setText("Shimmer (local, dB):");

        shimmerLocDbValueLabel.setText("jLabel1");

        shimmerApq3DescriptionLabel.setText("Shimmer (apq3):");

        shimmerApq3ValueLabel.setText("jLabel1");

        shimmerApq5DescriptionLabel.setText("Shimmer (apq5):");

        shimmerApq5ValueLabel.setText("jLabel2");

        shimmerApq11DescriptionLabel.setText("Shimmer (apq11):");

        shimmerApq11ValueLabel.setText("jLabel2");

        shimmerDdaDescriptionLabel.setText("Shimmer (dda):");

        shimmerDdaValueLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shimmerLocDbDescriptionLabel)
                    .addComponent(shimmerLocDescriptionLabel)
                    .addComponent(shimmerApq3DescriptionLabel)
                    .addComponent(shimmerApq5DescriptionLabel)
                    .addComponent(shimmerApq11DescriptionLabel)
                    .addComponent(shimmerDdaDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shimmerLocDbValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(shimmerLocValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq5ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq11ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerApq3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shimmerDdaValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerLocDescriptionLabel)
                    .addComponent(shimmerLocValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerLocDbDescriptionLabel)
                    .addComponent(shimmerLocDbValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq3DescriptionLabel)
                    .addComponent(shimmerApq3ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq5DescriptionLabel)
                    .addComponent(shimmerApq5ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerApq11DescriptionLabel)
                    .addComponent(shimmerApq11ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shimmerDdaDescriptionLabel)
                    .addComponent(shimmerDdaValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("HNR"));

        hnrAutDescriptionLabel.setText("HNR (aut):");

        hnrNHDescriptionLabel.setText("HNR (nh):");

        hnrHNDescriptionLabel.setText("HNR (hn):");

        hnrAutValueLabel.setText("jLabel1");

        hnrNHValueLabel.setText("jLabel1");

        hnrHNValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hnrHNDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hnrHNValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hnrAutDescriptionLabel)
                            .addComponent(hnrNHDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hnrNHValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hnrAutValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hnrAutDescriptionLabel)
                    .addComponent(hnrAutValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hnrNHDescriptionLabel)
                    .addComponent(hnrNHValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hnrHNDescriptionLabel)
                    .addComponent(hnrHNValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Voice breaks"));

        voiceFracDescriptionLabel.setText("Voicing fraction:");

        voiceFracValueLabel.setText("jLabel1");

        voiceNBreaksDescriptionLabel.setText("Voicing nBreaks:");

        voiceNBreaksValueLabel.setText("jLabel1");

        voiceDegreeDescriptionLabel.setText("Voicing degree:");

        voiceDegreeValueLabel.setText("jLabel1");

        tptDescriptionLabel.setText("TPT:");
        tptDescriptionLabel.setToolTipText("Total pause time");

        tptValueLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voiceDegreeDescriptionLabel)
                    .addComponent(voiceNBreaksDescriptionLabel)
                    .addComponent(voiceFracDescriptionLabel)
                    .addComponent(tptDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voiceNBreaksValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voiceDegreeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voiceFracValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tptValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voiceFracDescriptionLabel)
                    .addComponent(voiceFracValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voiceNBreaksDescriptionLabel)
                    .addComponent(voiceNBreaksValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voiceDegreeDescriptionLabel)
                    .addComponent(voiceDegreeValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tptDescriptionLabel)
                    .addComponent(tptValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Energy"));

        meanEnergyDescriptionLabel.setText("E (mean):");

        meanEnergyValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(meanEnergyDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanEnergyValueLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanEnergyDescriptionLabel)
                    .addComponent(meanEnergyValueLabel))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showGraphButton)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(showGraphButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        f0Table.setModel(f0TableModel);
        jScrollPane2.setViewportView(f0Table);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        logger.debug("Showing pitch chart from " + csvResultFile.getName());
        if (f0Graph == null) {
            F0PitchCharts charts = new F0PitchCharts();
            f0Graph = new GraphWindow(csvResultFile.getName(), charts.createChart(csvResultFile));
            f0Graph.setVisible(true);
        } else {
            f0Graph.setVisible(true);
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void loadF0Table() {
        String[] csvLine = null;
        try {
            CSVReader reader = new CSVReader(new FileReader(csvResultFile), ' ');
            reader.readNext();
            f0TableModel.setColumnIdentifiers(new String[] {"Time min (s)", "Time max (s)", "F0 mean (Hz)", "F0 min (Hz)", "F0 max (Hz)", "F0 stdev (Hz)", "F0 VR (Hz)", "rel F0 stdev (%)", "rel F0 VR (%)"});
            while ((csvLine = reader.readNext()) != null) {
                f0TableModel.addRow(csvLine);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load pitch table from CSV file " + csvResultFile.getName(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load formants table from CSV file!", ex);
        }
        f0Table.setModel(f0TableModel);
        f0TableModel.fireTableDataChanged();
        
        try {
            CSVReader reader = new CSVReader(new FileReader(csvStatsFile), ' ');
            reader.readNext();
            csvLine = reader.readNext();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load pitch table from CSV file " + csvStatsFile.getName(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.error("Failed to load pitch table from CSV file!", ex);
        }
        
        // jitter
        jitterLocValueLabel.setText(csvLine[0]);
        jitterLocAbsValueLabel.setText(csvLine[1]);
        jitterRapValueLabel.setText(csvLine[2]);
        jitterPpq5ValueLabel.setText(csvLine[3]);
        jitterDdpValueLabel.setText(csvLine[4]);
        
        // shimmer
        shimmerLocValueLabel.setText(csvLine[5]);
        shimmerLocDbValueLabel.setText(csvLine[6]);
        shimmerApq3ValueLabel.setText(csvLine[7]);
        shimmerApq5ValueLabel.setText(csvLine[8]);
        shimmerApq11ValueLabel.setText(csvLine[9]);
        shimmerDdaValueLabel.setText(csvLine[10]);

        // F0
        meanValueLabel.setText(csvLine[11] + " Hz");
        medianValuleLabel.setText(csvLine[12] + " Hz");
        stdevValueLabel.setText(csvLine[13] + " Hz");
        minValueLabel.setText(csvLine[14] + " Hz");
        maxValueLabel.setText(csvLine[15] + " Hz");
        varValueLabel.setText("TBD");
        vrValueLabel.setText(csvLine[16] + " Hz");
        relVRValueLabel.setText(csvLine[17]);
        relStdevValueLabel.setText(csvLine[18]);
        
        // HNR
        hnrAutValueLabel.setText(csvLine[19]);
        hnrNHValueLabel.setText(csvLine[20]);
        hnrHNValueLabel.setText(csvLine[21] + " dB");
        
        // voicing
        voiceFracValueLabel.setText(csvLine[22]);
        voiceNBreaksValueLabel.setText(csvLine[23]);
        voiceDegreeValueLabel.setText(csvLine[24]);
        tptValueLabel.setText(csvLine[27]);
        
        // energy
//        meanEnergyValueLabel.setText(String.valueOf(CalcUtilities.mean());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable f0Table;
    private javax.swing.JLabel hnrAutDescriptionLabel;
    private javax.swing.JLabel hnrAutValueLabel;
    private javax.swing.JLabel hnrHNDescriptionLabel;
    private javax.swing.JLabel hnrHNValueLabel;
    private javax.swing.JLabel hnrNHDescriptionLabel;
    private javax.swing.JLabel hnrNHValueLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jitterDdpDescriptionLabel;
    private javax.swing.JLabel jitterDdpValueLabel;
    private javax.swing.JLabel jitterLocAbsDescriptionLabel;
    private javax.swing.JLabel jitterLocAbsValueLabel;
    private javax.swing.JLabel jitterLocDescriptionLabel;
    private javax.swing.JLabel jitterLocValueLabel;
    private javax.swing.JLabel jitterPpq5DescriptionLabel;
    private javax.swing.JLabel jitterPpq5ValueLabel;
    private javax.swing.JLabel jitterRapDescriptionLabel;
    private javax.swing.JLabel jitterRapValueLabel;
    private javax.swing.JLabel maxDescriptionLabel;
    private javax.swing.JLabel maxValueLabel;
    private javax.swing.JLabel meanDescriptionLabel;
    private javax.swing.JLabel meanEnergyDescriptionLabel;
    private javax.swing.JLabel meanEnergyValueLabel;
    private javax.swing.JLabel meanValueLabel;
    private javax.swing.JLabel medianDescriptionLabel;
    private javax.swing.JLabel medianValuleLabel;
    private javax.swing.JLabel minDescriptionLabel;
    private javax.swing.JLabel minValueLabel;
    private javax.swing.JLabel relStdevDescriptionLabel;
    private javax.swing.JLabel relStdevValueLabel;
    private javax.swing.JLabel relVRDescriptionLabel;
    private javax.swing.JLabel relVRValueLabel;
    private javax.swing.JLabel shimmerApq11DescriptionLabel;
    private javax.swing.JLabel shimmerApq11ValueLabel;
    private javax.swing.JLabel shimmerApq3DescriptionLabel;
    private javax.swing.JLabel shimmerApq3ValueLabel;
    private javax.swing.JLabel shimmerApq5DescriptionLabel;
    private javax.swing.JLabel shimmerApq5ValueLabel;
    private javax.swing.JLabel shimmerDdaDescriptionLabel;
    private javax.swing.JLabel shimmerDdaValueLabel;
    private javax.swing.JLabel shimmerLocDbDescriptionLabel;
    private javax.swing.JLabel shimmerLocDbValueLabel;
    private javax.swing.JLabel shimmerLocDescriptionLabel;
    private javax.swing.JLabel shimmerLocValueLabel;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JLabel stdevDescriptionLabel;
    private javax.swing.JLabel stdevValueLabel;
    private javax.swing.JLabel tptDescriptionLabel;
    private javax.swing.JLabel tptValueLabel;
    private javax.swing.JLabel varDescriptionLabel;
    private javax.swing.JLabel varValueLabel;
    private javax.swing.JLabel voiceDegreeDescriptionLabel;
    private javax.swing.JLabel voiceDegreeValueLabel;
    private javax.swing.JLabel voiceFracDescriptionLabel;
    private javax.swing.JLabel voiceFracValueLabel;
    private javax.swing.JLabel voiceNBreaksDescriptionLabel;
    private javax.swing.JLabel voiceNBreaksValueLabel;
    private javax.swing.JLabel vrDescriptionLabel;
    private javax.swing.JLabel vrValueLabel;
    // End of variables declaration//GEN-END:variables
}
