package feec.cz.brno.speechproc.main;

import feec.cz.brno.speechproc.calc.api.f0.F0Impl;
import feec.cz.brno.speechproc.calc.api.formants.FormantsImpl;
import feec.cz.brno.speechproc.calc.api.intensity.IntensityImpl;
import feec.cz.brno.speechproc.calc.api.params.ScriptParameter;
import feec.cz.brno.speechproc.calc.api.params.ScriptParameters;
import feec.cz.brno.speechproc.calc.api.runscript.PraatScript;
import feec.cz.brno.speechproc.calc.api.runscript.ScriptRunException;
import feec.cz.brno.speechproc.calc.api.runscript.ScriptRunner;
import feec.cz.brno.speechproc.gui.Icons;
import feec.cz.brno.speechproc.gui.JTabbedPaneCloseButton;
import feec.cz.brno.speechproc.gui.f0.F0ParamsDialog;
import feec.cz.brno.speechproc.gui.formants.FormantCharts;
import feec.cz.brno.speechproc.gui.formants.FormantParamsDialog;
import feec.cz.brno.speechproc.gui.results.ResultPanel;
import feec.cz.brno.speechproc.gui.soundlist.SoundFilesTableModel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.commons.io.FileUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static feec.cz.brno.speechproc.calc.api.f0.IF0.OUTPUT_FOLDER_F0;
import static feec.cz.brno.speechproc.calc.api.formants.IFormants.OUTPUT_FOLDER_FORMANTS;

/**
 *
 * @author mira
 */
public class SpeechProc extends javax.swing.JFrame {

    private final static Logger logger = LogManager.getLogger(SpeechProc.class);
    
    public static final String FS = System.getProperty("file.separator");
    public static final String USER_DIR = System.getProperty("user.dir");

    private SoundFilesTableModel soundFilesTableModel = new SoundFilesTableModel();
    private TableRowSorter<TableModel> searchFieldRowSorter = new TableRowSorter<>(soundFilesTableModel);
    
    private FormantsImpl formantsTask;
    private F0Impl f0Task;
    private IntensityImpl intensityTask;

    /**
     * Creates new form SpeechProc
     */
    public SpeechProc() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            logger.error("Cannot set Nimbus Look and feel.", e);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        praatScriptBtn = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        centerSplitPanel = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        addSoundFileBtn = new javax.swing.JButton();
        removeSoundFileBtn = new javax.swing.JButton();
        soundFilesListScrollPanel = new javax.swing.JScrollPane();
        soundFilesTable = new javax.swing.JTable();
        searchFileTextField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        centerTabbedPanel = new JTabbedPaneCloseButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openSoundFilesMenuItem = new javax.swing.JMenuItem();
        praatScriptMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        formantsMenuItem = new javax.swing.JMenuItem();
        f0MenuItem = new javax.swing.JMenuItem();
        intensityMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speech PROC");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(1078, 980));

        toolBar.setRollover(true);

        praatScriptBtn.setText("Run praat script");
        praatScriptBtn.setToolTipText("Run praat script...");
        praatScriptBtn.setFocusable(false);
        praatScriptBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        praatScriptBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        praatScriptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praatScriptBtnActionPerformed(evt);
            }
        });
        toolBar.add(praatScriptBtn);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));
        bottomPanel.add(progressLabel);

        progressBar.setStringPainted(true);
        bottomPanel.add(progressBar);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerSplitPanel.setDividerLocation(300);
        centerSplitPanel.setResizeWeight(0.3);
        centerSplitPanel.setAutoscrolls(true);
        centerSplitPanel.setOneTouchExpandable(true);

        leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input files", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        addSoundFileBtn.setIcon(Icons.PLUS_ICON);
        addSoundFileBtn.setToolTipText("Add file");
        addSoundFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoundFileBtnActionPerformed(evt);
            }
        });

        removeSoundFileBtn.setIcon(Icons.MINUS_ICON);
        removeSoundFileBtn.setToolTipText("Remove file");
        removeSoundFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSoundFileBtnActionPerformed(evt);
            }
        });

        soundFilesTableModel.setColumnIdentifiers(new String[] { "Name", "Path", "Size"});
        for (int column = 0; column < soundFilesTable.getColumnCount(); column++) {
            soundFilesTableModel.addColumn(soundFilesTable.getColumnName(column));
        }
        soundFilesTable.setAutoCreateRowSorter(true);
        soundFilesTable.setModel(soundFilesTableModel);
        soundFilesTable.setRowSorter(searchFieldRowSorter);
        soundFilesTable.setGridColor(new java.awt.Color(255, 255, 255));
        soundFilesTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        soundFilesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soundFilesTableKeyReleased(evt);
            }
        });
        soundFilesListScrollPanel.setViewportView(soundFilesTable);

        searchFileTextField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = searchFileTextField.getText();

                if (text.trim().length() == 0) {
                    searchFieldRowSorter.setRowFilter(null);
                } else {
                    searchFieldRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = searchFileTextField.getText();

                if (text.trim().length() == 0) {
                    searchFieldRowSorter.setRowFilter(null);
                } else {
                    searchFieldRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
        searchFileTextField.setMaximumSize(new java.awt.Dimension(2147483647, 32));

        searchLabel.setText("Search:");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soundFilesListScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(addSoundFileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeSoundFileBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soundFilesListScrollPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSoundFileBtn)
                    .addComponent(removeSoundFileBtn)))
        );

        centerSplitPanel.setLeftComponent(leftPanel);

        centerTabbedPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                centerTabbedPanelKeyPressed(evt);
            }
        });
        centerSplitPanel.setRightComponent(centerTabbedPanel);

        getContentPane().add(centerSplitPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openSoundFilesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openSoundFilesMenuItem.setText("Open sound files...");
        openSoundFilesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSoundFilesMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openSoundFilesMenuItem);

        praatScriptMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        praatScriptMenuItem.setMnemonic('s');
        praatScriptMenuItem.setText("Run praat script...");
        praatScriptMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praatScriptMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(praatScriptMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Parameters");

        formantsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        formantsMenuItem.setMnemonic('t');
        formantsMenuItem.setText("Formants listing");
        formantsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formantsMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(formantsMenuItem);

        f0MenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        f0MenuItem.setMnemonic('p');
        f0MenuItem.setText("F0 (pitch)");
        f0MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f0MenuItemActionPerformed(evt);
            }
        });
        editMenu.add(f0MenuItem);

        intensityMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        intensityMenuItem.setMnemonic('d');
        intensityMenuItem.setText("Intensity");
        intensityMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensityMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(intensityMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        FileUtils.deleteQuietly(OUTPUT_FOLDER_F0);
        FileUtils.deleteQuietly(OUTPUT_FOLDER_FORMANTS);
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void formantsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formantsMenuItemActionPerformed
        List<File> soundFiles = getSelectedSoundFiles();

        if (soundFiles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No sound file selected!", "No file.", JOptionPane.WARNING_MESSAGE);
            return;
        }

        FormantParamsDialog paramsDialog = new FormantParamsDialog(this);
        paramsDialog.setVisible(true);
        
        if (paramsDialog.isOk()) {

            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            ResultPanel resultPanel = new ResultPanel();
            centerTabbedPanel.add("Formants", resultPanel);

            formantsTask = new FormantsImpl(this, paramsDialog, soundFiles, resultPanel.getResultTableModel(), progressLabel);
            progressBar.setValue(0);
            formantsTask.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
                if ("progress".equals(evt1.getPropertyName())) {
                    int progress = (Integer) evt1.getNewValue();
                    progressBar.setValue(progress);
                }
            });
            formantsTask.execute();
        }
    }//GEN-LAST:event_formantsMenuItemActionPerformed

    private void removeSoundFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSoundFileBtnActionPerformed
        removeSelectedRows();
    }//GEN-LAST:event_removeSoundFileBtnActionPerformed

    private void openSoundFilesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSoundFilesMenuItemActionPerformed
        addSoundFiles();
    }//GEN-LAST:event_openSoundFilesMenuItemActionPerformed

    private void addSoundFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoundFileBtnActionPerformed
        addSoundFiles();
    }//GEN-LAST:event_addSoundFileBtnActionPerformed

    private void praatScriptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praatScriptBtnActionPerformed
        runPraatScript();
    }//GEN-LAST:event_praatScriptBtnActionPerformed

    private void praatScriptMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praatScriptMenuItemActionPerformed
        runPraatScript();
    }//GEN-LAST:event_praatScriptMenuItemActionPerformed

    private void f0MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f0MenuItemActionPerformed
        List<File> soundFiles = getSelectedSoundFiles();

        if (soundFiles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No sound file selected!", "No file.", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        F0ParamsDialog paramsDialog = new F0ParamsDialog(this);
        paramsDialog.setVisible(true);
        
        if (paramsDialog.isOk()) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            ResultPanel resultPanel = new ResultPanel();
            centerTabbedPanel.add("F0 pitch", resultPanel);

            f0Task = new F0Impl(this, paramsDialog, soundFiles, resultPanel.getResultTableModel(), progressLabel);
            progressBar.setValue(0);
            f0Task.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
                if ("progress".equals(evt1.getPropertyName())) {
                    int progress = (Integer) evt1.getNewValue();
                    progressBar.setValue(progress);
                }
            });
            f0Task.execute();
        }
    }//GEN-LAST:event_f0MenuItemActionPerformed

    private void soundFilesTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soundFilesTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            removeSelectedRows();
        }
    }//GEN-LAST:event_soundFilesTableKeyReleased

    private void centerTabbedPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centerTabbedPanelKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_W) {
            centerTabbedPanel.remove(centerTabbedPanel.getSelectedIndex());
        }
    }//GEN-LAST:event_centerTabbedPanelKeyPressed

    private void intensityMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        List<File> soundFiles = getSelectedSoundFiles();

        if (soundFiles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No sound file selected!", "No file.", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        ResultPanel resultPanel = new ResultPanel();
        centerTabbedPanel.add("Intensity", resultPanel);
        
        intensityTask = new IntensityImpl(this, soundFiles, resultPanel.getResultTableModel(), progressLabel);
        progressBar.setValue(0);
        intensityTask.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            if ("progress".equals(evt1.getPropertyName())) {
                int progress = (Integer) evt1.getNewValue();
                progressBar.setValue(progress);
            }
        });
        intensityTask.execute();
    }                                                                                

    private void addSoundFiles() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setDialogTitle("Open sound file");
        // TODO use user.home
//        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setCurrentDirectory(new File("/media/mira/0f00c26e-7ed7-4b05-99c3-763797a05b44/mira/School/2016_17/DIPLOMKA/PAR_CZ_001/K1004/"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("Sound files (*.wav, *.mp3)", "wav", "mp3"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            List<File> list = new ArrayList<>(Arrays.asList(fileChooser.getSelectedFiles()));
            list.forEach(file -> {
                logger.debug("Opening sound file: {}", file.getAbsoluteFile());
                soundFilesTableModel.addRow(file);
            });
        } else {
            logger.trace("Open sound files cancelled by user.");
        }
    }
    
    private void removeSelectedRows() {
        if (soundFilesTable.getSelectedRowCount() > 0) {
            List<Vector> selectedRows = new ArrayList<>(25);
            Vector rowData = soundFilesTableModel.getDataVector();
            for (int row : soundFilesTable.getSelectedRows()) {
                int modelRow = soundFilesTable.convertRowIndexToModel(row);
                Vector rowValue = (Vector) rowData.get(modelRow);
                selectedRows.add(rowValue);
            }

            for (Vector rowValue : selectedRows) {
                int rowIndex = rowData.indexOf(rowValue);
                soundFilesTableModel.removeRow(rowIndex);
            }
        }
    }

    private void runPraatScript() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Open praat script");
        fileChooser.setMultiSelectionEnabled(rootPaneCheckingEnabled);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileFilter(new FileNameExtensionFilter("Praat script (*.praat)", "praat"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ScriptParameters parameters = new ScriptParameters();
            File praatScript = fileChooser.getSelectedFile();
            List<File> soundFiles = getSelectedSoundFiles();

            if (soundFiles.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No sound file selected!", "No file.", JOptionPane.WARNING_MESSAGE);
                return;
            }

            for (File soundFile : soundFiles) {

                parameters.add(new ScriptParameter("soundFilePath", soundFile.getAbsolutePath()));

//            parameters.add(soundFile.getCanonicalPath().replaceFirst(soundFile.getName(), "test.csv"));
                parameters.add(new ScriptParameter("outputFile", "./formantsListings.csv"));

                ScriptRunner praat = new PraatScript(praatScript, parameters);
                try {
                    praat.runScript();
                } catch (IOException | InterruptedException | ScriptRunException ex) {
                    logger.error("Praat script run has failed: ", ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Praat script has finished successfully.", "Success!", JOptionPane.INFORMATION_MESSAGE);

                FormantCharts graph = new FormantCharts();
                centerTabbedPanel.add("Formants listing", graph.createFormantChart(new File("formantsListings.csv")));
            }
        }
    }

    private List<File> getSelectedSoundFiles() {
        List<File> selectedSoundFiles = new ArrayList<>();
        File soundFile;

        for (int i = 0; i < soundFilesTable.getSelectedRows().length; i++) {
            soundFile = (File) soundFilesTableModel.getFileFromRow(soundFilesTable.getSelectedRows()[i]);
            selectedSoundFiles.add(soundFile);
        }

        return selectedSoundFiles;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpeechProc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SpeechProc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addSoundFileBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JSplitPane centerSplitPanel;
    private javax.swing.JTabbedPane centerTabbedPanel;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem f0MenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem formantsMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem intensityMenuItem;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openSoundFilesMenuItem;
    private javax.swing.JButton praatScriptBtn;
    private javax.swing.JMenuItem praatScriptMenuItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton removeSoundFileBtn;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JTextField searchFileTextField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JScrollPane soundFilesListScrollPanel;
    private javax.swing.JTable soundFilesTable;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

}
